.include "macros.inc"
.section .text

ARM_FUNC_START sub_20B82D8
sub_20B82D8:
.incbin "fe11-arm9-base.bin", 0xB82D8, 0xB8400 - 0xB82D8

ARM_FUNC_START sub_20B8400
sub_20B8400:
.incbin "fe11-arm9-base.bin", 0xB8400, 0xB8418 - 0xB8400

ARM_FUNC_START sub_20B8418
sub_20B8418:
.incbin "fe11-arm9-base.bin", 0xB8418, 0xB84CC - 0xB8418

ARM_FUNC_START sub_20B84CC
sub_20B84CC:
.incbin "fe11-arm9-base.bin", 0xB84CC, 0xB84FC - 0xB84CC

ARM_FUNC_START sub_20B84FC
sub_20B84FC:
.incbin "fe11-arm9-base.bin", 0xB84FC, 0xB8584 - 0xB84FC

ARM_FUNC_START sub_20B8584
sub_20B8584:
.incbin "fe11-arm9-base.bin", 0xB8584, 0xB8834 - 0xB8584

ARM_FUNC_START sub_20B8834
sub_20B8834:
.incbin "fe11-arm9-base.bin", 0xB8834, 0xB891C - 0xB8834

ARM_FUNC_START sub_20B891C
sub_20B891C:
.incbin "fe11-arm9-base.bin", 0xB891C, 0xB89A4 - 0xB891C

ARM_FUNC_START sub_20B89A4
sub_20B89A4:
.incbin "fe11-arm9-base.bin", 0xB89A4, 0xB89E8 - 0xB89A4

ARM_FUNC_START sub_20B89E8
sub_20B89E8:
.incbin "fe11-arm9-base.bin", 0xB89E8, 0xB8A64 - 0xB89E8

ARM_FUNC_START sub_20B8A64
sub_20B8A64:
.incbin "fe11-arm9-base.bin", 0xB8A64, 0xB8A9C - 0xB8A64

ARM_FUNC_START sub_20B8A9C
sub_20B8A9C:
.incbin "fe11-arm9-base.bin", 0xB8A9C, 0xB8AB0 - 0xB8A9C

ARM_FUNC_START sub_20B8AB0
sub_20B8AB0:
.incbin "fe11-arm9-base.bin", 0xB8AB0, 0xB8ACC - 0xB8AB0

ARM_FUNC_START sub_20B8ACC
sub_20B8ACC:
.incbin "fe11-arm9-base.bin", 0xB8ACC, 0xB8B44 - 0xB8ACC

ARM_FUNC_START sub_20B8B44
sub_20B8B44:
.incbin "fe11-arm9-base.bin", 0xB8B44, 0xB8B64 - 0xB8B44

ARM_FUNC_START sub_20B8B64
sub_20B8B64:
.incbin "fe11-arm9-base.bin", 0xB8B64, 0xB8BC4 - 0xB8B64

ARM_FUNC_START sub_20B8BC4
sub_20B8BC4:
.incbin "fe11-arm9-base.bin", 0xB8BC4, 0xB8BF0 - 0xB8BC4

ARM_FUNC_START sub_20B8BF0
sub_20B8BF0:
.incbin "fe11-arm9-base.bin", 0xB8BF0, 0xB8C1C - 0xB8BF0

ARM_FUNC_START sub_20B8C1C
sub_20B8C1C:
.incbin "fe11-arm9-base.bin", 0xB8C1C, 0xB8C5C - 0xB8C1C

ARM_FUNC_START sub_20B8C5C
sub_20B8C5C:
.incbin "fe11-arm9-base.bin", 0xB8C5C, 0xB8D0C - 0xB8C5C

ARM_FUNC_START sub_20B8D0C
sub_20B8D0C:
.incbin "fe11-arm9-base.bin", 0xB8D0C, 0xB929C - 0xB8D0C

ARM_FUNC_START sub_20B929C
sub_20B929C:
.incbin "fe11-arm9-base.bin", 0xB929C, 0xB94E8 - 0xB929C

ARM_FUNC_START sub_20B94E8
sub_20B94E8:
.incbin "fe11-arm9-base.bin", 0xB94E8, 0xB97E4 - 0xB94E8

ARM_FUNC_START sub_20B97E4
sub_20B97E4:
.incbin "fe11-arm9-base.bin", 0xB97E4, 0xB9CC0 - 0xB97E4

ARM_FUNC_START sub_20B9CC0
sub_20B9CC0:
.incbin "fe11-arm9-base.bin", 0xB9CC0, 0xB9DE4 - 0xB9CC0

ARM_FUNC_START sub_20B9DE4
sub_20B9DE4:
.incbin "fe11-arm9-base.bin", 0xB9DE4, 0xBA548 - 0xB9DE4

ARM_FUNC_START sub_20BA548
sub_20BA548:
.incbin "fe11-arm9-base.bin", 0xBA548, 0xBAD6C - 0xBA548

ARM_FUNC_START sub_20BAD6C
sub_20BAD6C:
.incbin "fe11-arm9-base.bin", 0xBAD6C, 0xBAD98 - 0xBAD6C

ARM_FUNC_START sub_20BAD98
sub_20BAD98:
.incbin "fe11-arm9-base.bin", 0xBAD98, 0xBADDC - 0xBAD98

ARM_FUNC_START sub_20BADDC
sub_20BADDC:
.incbin "fe11-arm9-base.bin", 0xBADDC, 0xBAEF4 - 0xBADDC

ARM_FUNC_START sub_20BAEF4
sub_20BAEF4:
.incbin "fe11-arm9-base.bin", 0xBAEF4, 0xBB1DC - 0xBAEF4

ARM_FUNC_START sub_20BB1DC
sub_20BB1DC:
.incbin "fe11-arm9-base.bin", 0xBB1DC, 0xBB30C - 0xBB1DC

ARM_FUNC_START sub_20BB30C
sub_20BB30C:
.incbin "fe11-arm9-base.bin", 0xBB30C, 0xBB328 - 0xBB30C

ARM_FUNC_START sub_20BB328
sub_20BB328:
.incbin "fe11-arm9-base.bin", 0xBB328, 0xBB3F0 - 0xBB328

ARM_FUNC_START sub_20BB3F0
sub_20BB3F0:
.incbin "fe11-arm9-base.bin", 0xBB3F0, 0xBB470 - 0xBB3F0

ARM_FUNC_START sub_20BB470
sub_20BB470:
.incbin "fe11-arm9-base.bin", 0xBB470, 0xBB584 - 0xBB470

ARM_FUNC_START sub_20BB584
sub_20BB584:
.incbin "fe11-arm9-base.bin", 0xBB584, 0xBB5B8 - 0xBB584

ARM_FUNC_START sub_20BB5B8
sub_20BB5B8:
.incbin "fe11-arm9-base.bin", 0xBB5B8, 0xBB5F4 - 0xBB5B8

ARM_FUNC_START sub_20BB5F4
sub_20BB5F4:
.incbin "fe11-arm9-base.bin", 0xBB5F4, 0xBB660 - 0xBB5F4

ARM_FUNC_START sub_20BB660
sub_20BB660:
.incbin "fe11-arm9-base.bin", 0xBB660, 0xBC8AC - 0xBB660

ARM_FUNC_START sub_20BC8AC
sub_20BC8AC:
.incbin "fe11-arm9-base.bin", 0xBC8AC, 0xBC99C - 0xBC8AC

ARM_FUNC_START sub_20BC99C
sub_20BC99C:
.incbin "fe11-arm9-base.bin", 0xBC99C, 0xBCD84 - 0xBC99C

ARM_FUNC_START sub_20BCD84
sub_20BCD84:
.incbin "fe11-arm9-base.bin", 0xBCD84, 0xBCE1C - 0xBCD84

ARM_FUNC_START sub_20BCE1C
sub_20BCE1C:
.incbin "fe11-arm9-base.bin", 0xBCE1C, 0xBCEE4 - 0xBCE1C

ARM_FUNC_START sub_20BCEE4
sub_20BCEE4:
.incbin "fe11-arm9-base.bin", 0xBCEE4, 0xBCEF8 - 0xBCEE4

ARM_FUNC_START sub_20BCEF8
sub_20BCEF8:
.incbin "fe11-arm9-base.bin", 0xBCEF8, 0xBCF6C - 0xBCEF8

ARM_FUNC_START sub_20BCF6C
sub_20BCF6C:
.incbin "fe11-arm9-base.bin", 0xBCF6C, 0xBCF88 - 0xBCF6C

ARM_FUNC_START sub_20BCF88
sub_20BCF88:
.incbin "fe11-arm9-base.bin", 0xBCF88, 0xBCFA8 - 0xBCF88

ARM_FUNC_START sub_20BCFA8
sub_20BCFA8:
.incbin "fe11-arm9-base.bin", 0xBCFA8, 0xBE130 - 0xBCFA8

ARM_FUNC_START sub_20BE130
sub_20BE130:
.incbin "fe11-arm9-base.bin", 0xBE130, 0xBE158 - 0xBE130

ARM_FUNC_START sub_20BE158
sub_20BE158:
.incbin "fe11-arm9-base.bin", 0xBE158, 0xBE178 - 0xBE158

ARM_FUNC_START sub_20BE178
sub_20BE178:
.incbin "fe11-arm9-base.bin", 0xBE178, 0xBE234 - 0xBE178

ARM_FUNC_START sub_20BE234
sub_20BE234:
.incbin "fe11-arm9-base.bin", 0xBE234, 0xBE480 - 0xBE234

ARM_FUNC_START sub_20BE480
sub_20BE480:
.incbin "fe11-arm9-base.bin", 0xBE480, 0xBE48C - 0xBE480

ARM_FUNC_START sub_20BE48C
sub_20BE48C:
.incbin "fe11-arm9-base.bin", 0xBE48C, 0xBE4F8 - 0xBE48C

ARM_FUNC_START sub_20BE4F8
sub_20BE4F8:
.incbin "fe11-arm9-base.bin", 0xBE4F8, 0xBE548 - 0xBE4F8

ARM_FUNC_START sub_20BE548
sub_20BE548:
.incbin "fe11-arm9-base.bin", 0xBE548, 0xBE588 - 0xBE548

ARM_FUNC_START sub_20BE588
sub_20BE588:
.incbin "fe11-arm9-base.bin", 0xBE588, 0xBE654 - 0xBE588

ARM_FUNC_START sub_20BE654
sub_20BE654:
.incbin "fe11-arm9-base.bin", 0xBE654, 0xBE7D8 - 0xBE654

ARM_FUNC_START sub_20BE7D8
sub_20BE7D8:
.incbin "fe11-arm9-base.bin", 0xBE7D8, 0xBE874 - 0xBE7D8

ARM_FUNC_START sub_20BE874
sub_20BE874:
.incbin "fe11-arm9-base.bin", 0xBE874, 0xBEBF8 - 0xBE874

ARM_FUNC_START sub_20BEBF8
sub_20BEBF8:
.incbin "fe11-arm9-base.bin", 0xBEBF8, 0xBECD8 - 0xBEBF8

ARM_FUNC_START sub_20BECD8
sub_20BECD8:
.incbin "fe11-arm9-base.bin", 0xBECD8, 0xBEDB8 - 0xBECD8

ARM_FUNC_START sub_20BEDB8
sub_20BEDB8:
.incbin "fe11-arm9-base.bin", 0xBEDB8, 0xBF05C - 0xBEDB8

ARM_FUNC_START sub_20BF05C
sub_20BF05C:
.incbin "fe11-arm9-base.bin", 0xBF05C, 0xBF1DC - 0xBF05C

ARM_FUNC_START sub_20BF1DC
sub_20BF1DC:
.incbin "fe11-arm9-base.bin", 0xBF1DC, 0xBF284 - 0xBF1DC

ARM_FUNC_START sub_20BF284
sub_20BF284:
.incbin "fe11-arm9-base.bin", 0xBF284, 0xBF8A8 - 0xBF284

ARM_FUNC_START sub_20BF8A8
sub_20BF8A8:
.incbin "fe11-arm9-base.bin", 0xBF8A8, 0xBF93C - 0xBF8A8

ARM_FUNC_START sub_20BF93C
sub_20BF93C:
.incbin "fe11-arm9-base.bin", 0xBF93C, 0xBF950 - 0xBF93C

ARM_FUNC_START sub_20BF950
sub_20BF950:
.incbin "fe11-arm9-base.bin", 0xBF950, 0xBF9C0 - 0xBF950

ARM_FUNC_START sub_20BF9C0
sub_20BF9C0:
.incbin "fe11-arm9-base.bin", 0xBF9C0, 0xBF9EC - 0xBF9C0

ARM_FUNC_START sub_20BF9EC
sub_20BF9EC:
.incbin "fe11-arm9-base.bin", 0xBF9EC, 0xBFA7C - 0xBF9EC

ARM_FUNC_START sub_20BFA7C
sub_20BFA7C:
.incbin "fe11-arm9-base.bin", 0xBFA7C, 0xBFAFC - 0xBFA7C

ARM_FUNC_START sub_20BFAFC
sub_20BFAFC:
.incbin "fe11-arm9-base.bin", 0xBFAFC, 0xBFB14 - 0xBFAFC

ARM_FUNC_START sub_20BFB14
sub_20BFB14:
.incbin "fe11-arm9-base.bin", 0xBFB14, 0xBFB3C - 0xBFB14

ARM_FUNC_START sub_20BFB3C
sub_20BFB3C:
.incbin "fe11-arm9-base.bin", 0xBFB3C, 0xBFB4C - 0xBFB3C

ARM_FUNC_START sub_20BFB4C
sub_20BFB4C:
.incbin "fe11-arm9-base.bin", 0xBFB4C, 0xBFB8C - 0xBFB4C

ARM_FUNC_START sub_20BFB8C
sub_20BFB8C:
.incbin "fe11-arm9-base.bin", 0xBFB8C, 0xBFBAC - 0xBFB8C

ARM_FUNC_START sub_20BFBAC
sub_20BFBAC:
.incbin "fe11-arm9-base.bin", 0xBFBAC, 0xBFBC4 - 0xBFBAC

ARM_FUNC_START sub_20BFBC4
sub_20BFBC4:
.incbin "fe11-arm9-base.bin", 0xBFBC4, 0xBFBCC - 0xBFBC4

ARM_FUNC_START sub_20BFBCC
sub_20BFBCC:
.incbin "fe11-arm9-base.bin", 0xBFBCC, 0xBFDD0 - 0xBFBCC

ARM_FUNC_START sub_20BFDD0
sub_20BFDD0:
.incbin "fe11-arm9-base.bin", 0xBFDD0, 0xC017C - 0xBFDD0

ARM_FUNC_START sub_20C017C
sub_20C017C:
.incbin "fe11-arm9-base.bin", 0xC017C, 0xC01C4 - 0xC017C

ARM_FUNC_START sub_20C01C4
sub_20C01C4:
.incbin "fe11-arm9-base.bin", 0xC01C4, 0xC01E8 - 0xC01C4

ARM_FUNC_START sub_20C01E8
sub_20C01E8:
.incbin "fe11-arm9-base.bin", 0xC01E8, 0xC0200 - 0xC01E8

ARM_FUNC_START sub_20C0200
sub_20C0200:
.incbin "fe11-arm9-base.bin", 0xC0200, 0xC0220 - 0xC0200

ARM_FUNC_START sub_20C0220
sub_20C0220:
.incbin "fe11-arm9-base.bin", 0xC0220, 0xC0238 - 0xC0220

ARM_FUNC_START sub_20C0238
sub_20C0238:
.incbin "fe11-arm9-base.bin", 0xC0238, 0xC0258 - 0xC0238

ARM_FUNC_START sub_20C0258
sub_20C0258:
.incbin "fe11-arm9-base.bin", 0xC0258, 0xC0270 - 0xC0258

ARM_FUNC_START sub_20C0270
sub_20C0270:
.incbin "fe11-arm9-base.bin", 0xC0270, 0xC0290 - 0xC0270

ARM_FUNC_START sub_20C0290
sub_20C0290:
.incbin "fe11-arm9-base.bin", 0xC0290, 0xC02C0 - 0xC0290

ARM_FUNC_START sub_20C02C0
sub_20C02C0:
.incbin "fe11-arm9-base.bin", 0xC02C0, 0xC02EC - 0xC02C0

ARM_FUNC_START sub_20C02EC
sub_20C02EC:
.incbin "fe11-arm9-base.bin", 0xC02EC, 0xC0708 - 0xC02EC

ARM_FUNC_START sub_20C0708
sub_20C0708:
.incbin "fe11-arm9-base.bin", 0xC0708, 0xC0794 - 0xC0708

ARM_FUNC_START sub_20C0794
sub_20C0794:
.incbin "fe11-arm9-base.bin", 0xC0794, 0xC07D4 - 0xC0794

ARM_FUNC_START sub_20C07D4
sub_20C07D4:
.incbin "fe11-arm9-base.bin", 0xC07D4, 0xC0810 - 0xC07D4

ARM_FUNC_START sub_20C0810
sub_20C0810:
.incbin "fe11-arm9-base.bin", 0xC0810, 0xC0B74 - 0xC0810

ARM_FUNC_START sub_20C0B74
sub_20C0B74:
.incbin "fe11-arm9-base.bin", 0xC0B74, 0xC0D28 - 0xC0B74

ARM_FUNC_START sub_20C0D28
sub_20C0D28:
.incbin "fe11-arm9-base.bin", 0xC0D28, 0xC1300 - 0xC0D28

ARM_FUNC_START sub_20C1300
sub_20C1300:
.incbin "fe11-arm9-base.bin", 0xC1300, 0xC1398 - 0xC1300

ARM_FUNC_START sub_20C1398
sub_20C1398:
.incbin "fe11-arm9-base.bin", 0xC1398, 0xC143C - 0xC1398

ARM_FUNC_START sub_20C143C
sub_20C143C:
.incbin "fe11-arm9-base.bin", 0xC143C, 0xC14D8 - 0xC143C

ARM_FUNC_START sub_20C14D8
sub_20C14D8:
.incbin "fe11-arm9-base.bin", 0xC14D8, 0xC1564 - 0xC14D8

ARM_FUNC_START sub_20C1564
sub_20C1564:
.incbin "fe11-arm9-base.bin", 0xC1564, 0xC16A8 - 0xC1564

ARM_FUNC_START sub_20C16A8
sub_20C16A8:
.incbin "fe11-arm9-base.bin", 0xC16A8, 0xC1738 - 0xC16A8

ARM_FUNC_START sub_20C1738
sub_20C1738:
.incbin "fe11-arm9-base.bin", 0xC1738, 0xC19B0 - 0xC1738

ARM_FUNC_START sub_20C19B0
sub_20C19B0:
.incbin "fe11-arm9-base.bin", 0xC19B0, 0xC19C0 - 0xC19B0

ARM_FUNC_START sub_20C19C0
sub_20C19C0:
.incbin "fe11-arm9-base.bin", 0xC19C0, 0xC1B70 - 0xC19C0

ARM_FUNC_START sub_20C1B70
sub_20C1B70:
.incbin "fe11-arm9-base.bin", 0xC1B70, 0xC1B7C - 0xC1B70

ARM_FUNC_START sub_20C1B7C
sub_20C1B7C:
.incbin "fe11-arm9-base.bin", 0xC1B7C, 0xC1BD8 - 0xC1B7C

ARM_FUNC_START sub_20C1BD8
sub_20C1BD8:
.incbin "fe11-arm9-base.bin", 0xC1BD8, 0xC1DE4 - 0xC1BD8

ARM_FUNC_START sub_20C1DE4
sub_20C1DE4:
.incbin "fe11-arm9-base.bin", 0xC1DE4, 0xC1DEC - 0xC1DE4

ARM_FUNC_START sub_20C1DEC
sub_20C1DEC:
.incbin "fe11-arm9-base.bin", 0xC1DEC, 0xC1FE0 - 0xC1DEC

ARM_FUNC_START sub_20C1FE0
sub_20C1FE0:
.incbin "fe11-arm9-base.bin", 0xC1FE0, 0xC2524 - 0xC1FE0

ARM_FUNC_START _fp_init
_fp_init: @ 0x020C2524
	bx lr

	arm_func_start sub_20C2528
sub_20C2528: @ 0x020C2528
	str lr, [sp, #-4]!
	mov r1, r0
	mov r0, #3
	svc #0x123456
	pop {pc}

	arm_func_start sub_20C253C
sub_20C253C: @ 0x020C253C
	str lr, [sp, #-4]!
	mov r1, #0
	mov r0, #7
	svc #0x123456
	pop {pc}

	arm_func_start sub_20C2550
sub_20C2550: @ 0x020C2550
	mov r1, #0
	mov r0, #0x18
	svc #0x123456
	mov pc, lr

	arm_func_start sub_20C2560
sub_20C2560: @ 0x020C2560
	push {r3, r4, r5, r6, r7, lr}
	mov r6, r2
	ldr r5, [r6]
	mov r7, r1
	cmp r5, #0
	mov r4, #0
	bls _020C25A8
_020C257C:
	bl sub_20C253C
	and r1, r0, #0xff
	cmp r1, #0xd
	strb r0, [r7, r4]
	cmpne r1, #0xa
	addeq r0, r4, #1
	streq r0, [r6]
	beq _020C25A8
	add r4, r4, #1
	cmp r4, r5
	blo _020C257C
_020C25A8:
	mov r0, #0
	pop {r3, r4, r5, r6, r7, pc}

	arm_func_start sub_20C25B0
sub_20C25B0: @ 0x020C25B0
	push {r4, r5, r6, lr}
	ldr r5, [r2]
	mov r6, r1
	cmp r5, #0
	mov r4, #0
	bls _020C25DC
_020C25C8:
	add r0, r6, r4
	bl sub_20C2528
	add r4, r4, #1
	cmp r4, r5
	blo _020C25C8
_020C25DC:
	mov r0, #0
	pop {r4, r5, r6, pc}

	arm_func_start sub_20C25E4
sub_20C25E4: @ 0x020C25E4
	mov r0, #0
	bx lr

	arm_func_start sub_20C25EC
sub_20C25EC: @ 0x020C25EC
	stm r0, {r4, r5, r6, r7, r8, sb, sl, fp, sp, lr}
	mov r0, #0
	bx lr

	arm_func_start sub_20C25F8
sub_20C25F8: @ 0x020C25F8
	ldm r0, {r4, r5, r6, r7, r8, sb, sl, fp, sp, lr}
	movs r0, r1
	moveq r0, #1
	bx lr

	arm_func_start sub_20C2608
sub_20C2608: @ 0x020C2608
	push {r4, lr}
	ldrsb r2, [r0]
	tst r2, #1
	bne _020C2628
	asr r2, r2, #1
	str r2, [r1]
	add r0, r0, #1
	pop {r4, pc}
_020C2628:
	tst r2, #2
	ldrb r4, [r0, #1]
	bne _020C2648
	asr r2, r2, #2
	orr r2, r4, r2, lsl #8
	str r2, [r1]
	add r0, r0, #2
	pop {r4, pc}
_020C2648:
	tst r2, #4
	ldrb lr, [r0, #2]
	bne _020C2670
	asr r3, r2, #3
	lsl r2, r4, #8
	orr r2, r2, r3, lsl #16
	orr r2, lr, r2
	str r2, [r1]
	add r0, r0, #3
	pop {r4, pc}
_020C2670:
	ldrb ip, [r0, #3]
	asr r3, r2, #3
	lsl r2, r4, #0x10
	orr r2, r2, r3, lsl #24
	orr r2, r2, lr, lsl #8
	orr r2, ip, r2
	str r2, [r1]
	add r0, r0, #4
	pop {r4, pc}

	arm_func_start sub_20C2694
sub_20C2694: @ 0x020C2694
	push {r4, lr}
	ldrb r2, [r0]
	tst r2, #1
	bne _020C26B4
	lsr r2, r2, #1
	str r2, [r1]
	add r0, r0, #1
	pop {r4, pc}
_020C26B4:
	tst r2, #2
	ldrb r4, [r0, #1]
	bne _020C26D4
	lsr r2, r2, #2
	orr r2, r4, r2, lsl #8
	str r2, [r1]
	add r0, r0, #2
	pop {r4, pc}
_020C26D4:
	tst r2, #4
	ldrb lr, [r0, #2]
	bne _020C26FC
	lsr r3, r2, #3
	lsl r2, r4, #8
	orr r2, r2, r3, lsl #16
	orr r2, lr, r2
	str r2, [r1]
	add r0, r0, #3
	pop {r4, pc}
_020C26FC:
	ldrb ip, [r0, #3]
	lsr r3, r2, #3
	lsl r2, r4, #0x10
	orr r2, r2, r3, lsl #24
	orr r2, r2, lr, lsl #8
	orr r2, ip, r2
	str r2, [r1]
	add r0, r0, #4
	pop {r4, pc}

	arm_func_start sub_20C2720
sub_20C2720: @ 0x020C2720
	push {r4, r5, r6, lr}
	subs r6, r1, #1
	mov r5, #0
	bmi _020C277C
	mov r1, #0xc
_020C2734:
	add r3, r5, r6
	asr r4, r3, #1
	mul r3, r4, r1
	ldr ip, [r0, r3]
	add lr, r0, r3
	cmp r2, ip
	sublo r6, r4, #1
	blo _020C2774
	ldr r3, [lr, #4]
	bic r3, r3, #1
	add r3, ip, r3
	cmp r2, r3
	addhi r5, r4, #1
	bhi _020C2774
	mov r0, lr
	pop {r4, r5, r6, pc}
_020C2774:
	cmp r5, r6
	ble _020C2734
_020C277C:
	mov r0, #0
	pop {r4, r5, r6, pc}

	arm_func_start sub_20C2784
sub_20C2784: @ 0x020C2784
	push {r4, r5, r6, r7, r8, sb, lr}
	sub sp, sp, #0xc
	mov r4, r0
	mov sb, r1
	mov r2, #0
	str r2, [sb, #4]
	mov r0, sb
	mov r1, r4
	str r2, [sb, #8]
	bl sub_20C4570
	cmp r0, #0
	addeq sp, sp, #0xc
	popeq {r4, r5, r6, r7, r8, sb, pc}
	ldr r0, [sb, #0xc]
	ldr r1, [sb, #0x10]
	ldr r3, _020C2888 @ =0x2AAAAAAB
	sub r5, r1, r0
	smull r2, r1, r3, r5
	lsr r3, r5, #0x1f
	mov r2, r4
	add r1, r3, r1, asr #1
	bl sub_20C2720
	cmp r0, #0
	addeq sp, sp, #0xc
	popeq {r4, r5, r6, r7, r8, sb, pc}
	ldr r1, [r0, #4]
	tst r1, #1
	addne r1, r0, #8
	ldreq r1, [r0, #8]
	str r1, [sb, #4]
	ldr r1, [r0]
	str r1, [sb]
	ldr r1, [r0]
	ldr r0, [sb, #4]
	sub r7, r4, r1
	bl sub_20C4590
	mov r8, #0
	add r5, sp, #4
	add r4, sp, #0
	add r6, sp, #8
_020C2824:
	mov r1, r6
	bl sub_20C2694
	ldr r1, [sp, #8]
	cmp r1, #0
	addeq sp, sp, #0xc
	popeq {r4, r5, r6, r7, r8, sb, pc}
	mov r1, r5
	bl sub_20C2694
	mov r1, r4
	bl sub_20C2694
	ldr r1, [sp, #8]
	add r2, r8, r1
	cmp r7, r2
	addlo sp, sp, #0xc
	poplo {r4, r5, r6, r7, r8, sb, pc}
	ldr r1, [sp, #4]
	add r8, r2, r1
	cmp r7, r8
	bhi _020C2824
	ldr r1, [sb, #4]
	ldr r0, [sp]
	add r0, r1, r0
	str r0, [sb, #8]
	add sp, sp, #0xc
	pop {r4, r5, r6, r7, r8, sb, pc}
	.align 2, 0
_020C2888: .4byte 0x2AAAAAAB

	arm_func_start sub_20C288C
sub_20C288C: @ 0x020C288C
	ldr r0, [r0, #8]
	cmp r0, #0
	ldrneb r0, [r0]
	andne r0, r0, #0x1f
	moveq r0, #0
	and r0, r0, #0xff
	bx lr

ARM_FUNC_START sub_20C28A8
sub_20C28A8:
.incbin "fe11-arm9-base.bin", 0xC28A8, 0xC2C30 - 0xC28A8

ARM_FUNC_START sub_20C2C30
sub_20C2C30:
.incbin "fe11-arm9-base.bin", 0xC2C30, 0xC34E0 - 0xC2C30

ARM_FUNC_START sub_20C34E0
sub_20C34E0:
.incbin "fe11-arm9-base.bin", 0xC34E0, 0xC3634 - 0xC34E0

ARM_FUNC_START sub_20C3634
sub_20C3634:
.incbin "fe11-arm9-base.bin", 0xC3634, 0xC36B8 - 0xC3634

ARM_FUNC_START sub_20C36B8
sub_20C36B8:
.incbin "fe11-arm9-base.bin", 0xC36B8, 0xC3764 - 0xC36B8

ARM_FUNC_START sub_20C3764
sub_20C3764:
.incbin "fe11-arm9-base.bin", 0xC3764, 0xC37C4 - 0xC3764

ARM_FUNC_START sub_20C37C4
sub_20C37C4:
.incbin "fe11-arm9-base.bin", 0xC37C4, 0xC39A0 - 0xC37C4

ARM_FUNC_START sub_20C39A0
sub_20C39A0:
.incbin "fe11-arm9-base.bin", 0xC39A0, 0xC39FC - 0xC39A0

ARM_FUNC_START sub_20C39FC
sub_20C39FC:
.incbin "fe11-arm9-base.bin", 0xC39FC, 0xC3AE8 - 0xC39FC

ARM_FUNC_START sub_20C3AE8
sub_20C3AE8:
.incbin "fe11-arm9-base.bin", 0xC3AE8, 0xC3B10 - 0xC3AE8

ARM_FUNC_START sub_20C3B10
sub_20C3B10:
.incbin "fe11-arm9-base.bin", 0xC3B10, 0xC3B24 - 0xC3B10

ARM_FUNC_START sub_20C3B24
sub_20C3B24:
.incbin "fe11-arm9-base.bin", 0xC3B24, 0xC3B30 - 0xC3B24

ARM_FUNC_START __call_static_initializers
__call_static_initializers: @ 0x020C3B30
	push {r4, lr}
	ldr r4, _020C3B58 @ =__sinit__
	b 2f
1:
	.4byte 0xE12FFF30 @ blx r0
	add r4, r4, #4
2:
	cmp r4, #0
	ldrne r0, [r4]
	cmpne r0, #0
	bne 1b
	pop {r4, pc}
	.align 2, 0
_020C3B58: .4byte __sinit__

ARM_FUNC_START sub_20C3B5C
sub_20C3B5C:
.incbin "fe11-arm9-base.bin", 0xC3B5C, 0xC3BA0 - 0xC3B5C

ARM_FUNC_START sub_20C3BA0
sub_20C3BA0:
.incbin "fe11-arm9-base.bin", 0xC3BA0, 0xC3BFC - 0xC3BA0

ARM_FUNC_START sub_20C3BFC
sub_20C3BFC:
.incbin "fe11-arm9-base.bin", 0xC3BFC, 0xC3CB4 - 0xC3BFC

ARM_FUNC_START sub_20C3CB4
sub_20C3CB4:
.incbin "fe11-arm9-base.bin", 0xC3CB4, 0xC3D64 - 0xC3CB4

ARM_FUNC_START sub_20C3D64
sub_20C3D64:
.incbin "fe11-arm9-base.bin", 0xC3D64, 0xC3E88 - 0xC3D64

ARM_FUNC_START sub_20C3E88
sub_20C3E88:
.incbin "fe11-arm9-base.bin", 0xC3E88, 0xC3EB8 - 0xC3E88

ARM_FUNC_START sub_20C3EB8
sub_20C3EB8:
.incbin "fe11-arm9-base.bin", 0xC3EB8, 0xC3ECC - 0xC3EB8

ARM_FUNC_START sub_20C3ECC
sub_20C3ECC:
.incbin "fe11-arm9-base.bin", 0xC3ECC, 0xC3EE8 - 0xC3ECC

ARM_FUNC_START sub_20C3EE8
sub_20C3EE8:
.incbin "fe11-arm9-base.bin", 0xC3EE8, 0xC3EFC - 0xC3EE8

ARM_FUNC_START sub_20C3EFC
sub_20C3EFC:
.incbin "fe11-arm9-base.bin", 0xC3EFC, 0xC3F10 - 0xC3EFC

ARM_FUNC_START sub_20C3F10
sub_20C3F10:
.incbin "fe11-arm9-base.bin", 0xC3F10, 0xC3F2C - 0xC3F10

ARM_FUNC_START sub_20C3F2C
sub_20C3F2C:
.incbin "fe11-arm9-base.bin", 0xC3F2C, 0xC3F40 - 0xC3F2C

ARM_FUNC_START sub_20C3F40
sub_20C3F40:
.incbin "fe11-arm9-base.bin", 0xC3F40, 0xC3F5C - 0xC3F40

ARM_FUNC_START sub_20C3F5C
sub_20C3F5C:
.incbin "fe11-arm9-base.bin", 0xC3F5C, 0xC418C - 0xC3F5C

ARM_FUNC_START sub_20C418C
sub_20C418C:
.incbin "fe11-arm9-base.bin", 0xC418C, 0xC425C - 0xC418C

ARM_FUNC_START sub_20C425C
sub_20C425C:
.incbin "fe11-arm9-base.bin", 0xC425C, 0xC4268 - 0xC425C

ARM_FUNC_START sub_20C4268
sub_20C4268:
.incbin "fe11-arm9-base.bin", 0xC4268, 0xC4274 - 0xC4268

ARM_FUNC_START sub_20C4274
sub_20C4274:
.incbin "fe11-arm9-base.bin", 0xC4274, 0xC428C - 0xC4274

ARM_FUNC_START sub_20C428C
sub_20C428C:
.incbin "fe11-arm9-base.bin", 0xC428C, 0xC42A4 - 0xC428C

ARM_FUNC_START sub_20C42A4
sub_20C42A4:
.incbin "fe11-arm9-base.bin", 0xC42A4, 0xC42C4 - 0xC42A4

ARM_FUNC_START sub_20C42C4
sub_20C42C4:
.incbin "fe11-arm9-base.bin", 0xC42C4, 0xC4474 - 0xC42C4

ARM_FUNC_START sub_20C4474
sub_20C4474:
.incbin "fe11-arm9-base.bin", 0xC4474, 0xC44D0 - 0xC4474

ARM_FUNC_START sub_20C44D0
sub_20C44D0:
.incbin "fe11-arm9-base.bin", 0xC44D0, 0xC4570 - 0xC44D0

ARM_FUNC_START sub_20C4570
sub_20C4570:
.incbin "fe11-arm9-base.bin", 0xC4570, 0xC4590 - 0xC4570

ARM_FUNC_START sub_20C4590
sub_20C4590:
.incbin "fe11-arm9-base.bin", 0xC4590, 0xC45C0 - 0xC4590

ARM_FUNC_START sub_20C45C0
sub_20C45C0:
.incbin "fe11-arm9-base.bin", 0xC45C0, 0xC45F0 - 0xC45C0

ARM_FUNC_START sub_20C45F0
sub_20C45F0:
.incbin "fe11-arm9-base.bin", 0xC45F0, 0xC4638 - 0xC45F0

ARM_FUNC_START sub_20C4638
sub_20C4638:
.incbin "fe11-arm9-base.bin", 0xC4638, 0xC4684 - 0xC4638

ARM_FUNC_START sub_20C4684
sub_20C4684:
.incbin "fe11-arm9-base.bin", 0xC4684, 0xC4CDC - 0xC4684
