.include "macros.inc"
.section .text


ARM_FUNC_START OS_InitLock
OS_InitLock:
.incbin "fe11-arm9-base.bin", 0xA286C, 0xA2938 - 0xA286C

ARM_FUNC_START sub_20A2938
sub_20A2938:
.incbin "fe11-arm9-base.bin", 0xA2938, 0xA2984 - 0xA2938

ARM_FUNC_START sub_20A2984
sub_20A2984:
.incbin "fe11-arm9-base.bin", 0xA2984, 0xA2994 - 0xA2984

ARM_FUNC_START sub_20A2994
sub_20A2994:
.incbin "fe11-arm9-base.bin", 0xA2994, 0xA2A08 - 0xA2994

ARM_FUNC_START sub_20A2A08
sub_20A2A08:
.incbin "fe11-arm9-base.bin", 0xA2A08, 0xA2A18 - 0xA2A08

ARM_FUNC_START sub_20A2A18
sub_20A2A18:
.incbin "fe11-arm9-base.bin", 0xA2A18, 0xA2AA4 - 0xA2A18

ARM_FUNC_START sub_20A2AA4
sub_20A2AA4:
.incbin "fe11-arm9-base.bin", 0xA2AA4, 0xA2AB0 - 0xA2AA4

ARM_FUNC_START sub_20A2AB0
sub_20A2AB0:
.incbin "fe11-arm9-base.bin", 0xA2AB0, 0xA2AE8 - 0xA2AB0

ARM_FUNC_START sub_20A2AE8
sub_20A2AE8:
.incbin "fe11-arm9-base.bin", 0xA2AE8, 0xA2B00 - 0xA2AE8

ARM_FUNC_START sub_20A2B00
sub_20A2B00:
.incbin "fe11-arm9-base.bin", 0xA2B00, 0xA2B1C - 0xA2B00

ARM_FUNC_START sub_20A2B1C
sub_20A2B1C:
.incbin "fe11-arm9-base.bin", 0xA2B1C, 0xA2B68 - 0xA2B1C

ARM_FUNC_START sub_20A2B68
sub_20A2B68:
.incbin "fe11-arm9-base.bin", 0xA2B68, 0xA2B70 - 0xA2B68

ARM_FUNC_START OS_GetLockID
OS_GetLockID:
.incbin "fe11-arm9-base.bin", 0xA2B70, 0xA2BC8 - 0xA2B70

ARM_FUNC_START sub_20A2BC8
sub_20A2BC8:
.incbin "fe11-arm9-base.bin", 0xA2BC8, 0xA2BF8 - 0xA2BC8

ARM_FUNC_START sub_20A2BF8
sub_20A2BF8:
.incbin "fe11-arm9-base.bin", 0xA2BF8, 0xA2C20 - 0xA2BF8

ARM_FUNC_START sub_20A2C20
sub_20A2C20:
.incbin "fe11-arm9-base.bin", 0xA2C20, 0xA2C38 - 0xA2C20

ARM_FUNC_START sub_20A2C38
sub_20A2C38:
.incbin "fe11-arm9-base.bin", 0xA2C38, 0xA2C60 - 0xA2C38

ARM_FUNC_START sub_20A2C60
sub_20A2C60:
.incbin "fe11-arm9-base.bin", 0xA2C60, 0xA2C6C - 0xA2C60

ARM_FUNC_START sub_20A2C6C
sub_20A2C6C:
.incbin "fe11-arm9-base.bin", 0xA2C6C, 0xA2C84 - 0xA2C6C

ARM_FUNC_START sub_20A2C84
sub_20A2C84:
.incbin "fe11-arm9-base.bin", 0xA2C84, 0xA2CFC - 0xA2C84

ARM_FUNC_START OSi_RemoveLinkFromQueue
OSi_RemoveLinkFromQueue:
.incbin "fe11-arm9-base.bin", 0xA2CFC, 0xA2D30 - 0xA2CFC

ARM_FUNC_START sub_20A2D30
sub_20A2D30:
.incbin "fe11-arm9-base.bin", 0xA2D30, 0xA2D84 - 0xA2D30

ARM_FUNC_START sub_20A2D84
sub_20A2D84:
.incbin "fe11-arm9-base.bin", 0xA2D84, 0xA2DB4 - 0xA2D84

ARM_FUNC_START sub_20A2DB4
sub_20A2DB4:
.incbin "fe11-arm9-base.bin", 0xA2DB4, 0xA2E14 - 0xA2DB4

ARM_FUNC_START sub_20A2E14
sub_20A2E14:
.incbin "fe11-arm9-base.bin", 0xA2E14, 0xA2E5C - 0xA2E14

ARM_FUNC_START OSi_RescheduleThread
OSi_RescheduleThread:
.incbin "fe11-arm9-base.bin", 0xA2E5C, 0xA2F24 - 0xA2E5C

ARM_FUNC_START OS_InitThread
OS_InitThread:
.incbin "fe11-arm9-base.bin", 0xA2F24, 0xA3080 - 0xA2F24

ARM_FUNC_START sub_20A3080
sub_20A3080:
.incbin "fe11-arm9-base.bin", 0xA3080, 0xA317C - 0xA3080

ARM_FUNC_START sub_20A317C
sub_20A317C:
.incbin "fe11-arm9-base.bin", 0xA317C, 0xA319C - 0xA317C

ARM_FUNC_START sub_20A319C
sub_20A319C:
.incbin "fe11-arm9-base.bin", 0xA319C, 0xA31F8 - 0xA319C

ARM_FUNC_START sub_20A31F8
sub_20A31F8:
.incbin "fe11-arm9-base.bin", 0xA31F8, 0xA3230 - 0xA31F8

ARM_FUNC_START sub_20A3230
sub_20A3230:
.incbin "fe11-arm9-base.bin", 0xA3230, 0xA328C - 0xA3230

ARM_FUNC_START sub_20A328C
sub_20A328C:
.incbin "fe11-arm9-base.bin", 0xA328C, 0xA3308 - 0xA328C

ARM_FUNC_START sub_20A3308
sub_20A3308:
.incbin "fe11-arm9-base.bin", 0xA3308, 0xA3320 - 0xA3308

ARM_FUNC_START sub_20A3320
sub_20A3320:
.incbin "fe11-arm9-base.bin", 0xA3320, 0xA3350 - 0xA3320

ARM_FUNC_START sub_20A3350
sub_20A3350:
.incbin "fe11-arm9-base.bin", 0xA3350, 0xA3364 - 0xA3350

ARM_FUNC_START OS_SleepThread
OS_SleepThread:
.incbin "fe11-arm9-base.bin", 0xA3364, 0xA33B4 - 0xA3364

ARM_FUNC_START OS_WakeupThread
OS_WakeupThread:
.incbin "fe11-arm9-base.bin", 0xA33B4, 0xA341C - 0xA33B4

ARM_FUNC_START sub_20A341C
sub_20A341C:
.incbin "fe11-arm9-base.bin", 0xA341C, 0xA3444 - 0xA341C

ARM_FUNC_START sub_20A3444
sub_20A3444:
.incbin "fe11-arm9-base.bin", 0xA3444, 0xA346C - 0xA3444

ARM_FUNC_START sub_20A346C
sub_20A346C:
.incbin "fe11-arm9-base.bin", 0xA346C, 0xA3488 - 0xA346C

ARM_FUNC_START sub_20A3488
sub_20A3488:
.incbin "fe11-arm9-base.bin", 0xA3488, 0xA3540 - 0xA3488

ARM_FUNC_START sub_20A3540
sub_20A3540:
.incbin "fe11-arm9-base.bin", 0xA3540, 0xA35E8 - 0xA3540

ARM_FUNC_START sub_20A35E8
sub_20A35E8:
.incbin "fe11-arm9-base.bin", 0xA35E8, 0xA35F0 - 0xA35E8

ARM_FUNC_START sub_20A35F0
sub_20A35F0:
.incbin "fe11-arm9-base.bin", 0xA35F0, 0xA36AC - 0xA35F0

ARM_FUNC_START sub_20A36AC
sub_20A36AC:
.incbin "fe11-arm9-base.bin", 0xA36AC, 0xA36D4 - 0xA36AC

ARM_FUNC_START sub_20A36D4
sub_20A36D4:
.incbin "fe11-arm9-base.bin", 0xA36D4, 0xA36E4 - 0xA36D4

ARM_FUNC_START sub_20A36E4
sub_20A36E4:
.incbin "fe11-arm9-base.bin", 0xA36E4, 0xA3718 - 0xA36E4

ARM_FUNC_START sub_20A3718
sub_20A3718:
.incbin "fe11-arm9-base.bin", 0xA3718, 0xA374C - 0xA3718

ARM_FUNC_START sub_20A374C
sub_20A374C:
.incbin "fe11-arm9-base.bin", 0xA374C, 0xA3754 - 0xA374C

ARM_FUNC_START sub_20A3754
sub_20A3754:
.incbin "fe11-arm9-base.bin", 0xA3754, 0xA375C - 0xA3754

ARM_FUNC_START sub_20A375C
sub_20A375C:
.incbin "fe11-arm9-base.bin", 0xA375C, 0xA3764 - 0xA375C

ARM_FUNC_START sub_20A3764
sub_20A3764:
.incbin "fe11-arm9-base.bin", 0xA3764, 0xA37D0 - 0xA3764

ARM_FUNC_START sub_20A37D0
sub_20A37D0:
.incbin "fe11-arm9-base.bin", 0xA37D0, 0xA381C - 0xA37D0

ARM_FUNC_START sub_20A381C
sub_20A381C:
.incbin "fe11-arm9-base.bin", 0xA381C, 0xA3860 - 0xA381C

ARM_FUNC_START sub_20A3860
sub_20A3860:
.incbin "fe11-arm9-base.bin", 0xA3860, 0xA3868 - 0xA3860

ARM_FUNC_START OS_GetConsoleType
OS_GetConsoleType:
.incbin "fe11-arm9-base.bin", 0xA3868, 0xA3880 - 0xA3868

ARM_FUNC_START sub_20A3880
sub_20A3880:
.incbin "fe11-arm9-base.bin", 0xA3880, 0xA38A8 - 0xA3880

ARM_FUNC_START sub_20A38A8
sub_20A38A8:
.incbin "fe11-arm9-base.bin", 0xA38A8, 0xA393C - 0xA38A8

ARM_FUNC_START sub_20A393C
sub_20A393C:
.incbin "fe11-arm9-base.bin", 0xA393C, 0xA39E0 - 0xA393C

ARM_FUNC_START sub_20A39E0
sub_20A39E0:
.incbin "fe11-arm9-base.bin", 0xA39E0, 0xA3A7C - 0xA39E0

ARM_FUNC_START sub_20A3A7C
sub_20A3A7C:
.incbin "fe11-arm9-base.bin", 0xA3A7C, 0xA3AF8 - 0xA3A7C

ARM_FUNC_START sub_20A3AF8
sub_20A3AF8:
.incbin "fe11-arm9-base.bin", 0xA3AF8, 0xA3B10 - 0xA3AF8

ARM_FUNC_START OS_LockMutex
OS_LockMutex:
.incbin "fe11-arm9-base.bin", 0xA3B10, 0xA3B94 - 0xA3B10

ARM_FUNC_START OS_UnlockMutex
OS_UnlockMutex:
.incbin "fe11-arm9-base.bin", 0xA3B94, 0xA3BF0 - 0xA3B94

ARM_FUNC_START sub_20A3BF0
sub_20A3BF0:
.incbin "fe11-arm9-base.bin", 0xA3BF0, 0xA3C2C - 0xA3BF0

ARM_FUNC_START OS_TryLockMutex
OS_TryLockMutex:
.incbin "fe11-arm9-base.bin", 0xA3C2C, 0xA3CA0 - 0xA3C2C
