.include "macros.inc"
.section .text

ARM_FUNC_START sub_20A3DE4
sub_20A3DE4:
.incbin "fe11-arm9-base.bin", 0xA3DE4, 0xA3E04 - 0xA3DE4

ARM_FUNC_START sub_20A3E04
sub_20A3E04:
.incbin "fe11-arm9-base.bin", 0xA3E04, 0xA3E4C - 0xA3E04

ARM_FUNC_START sub_20A3E4C
sub_20A3E4C:
.incbin "fe11-arm9-base.bin", 0xA3E4C, 0xA3F50 - 0xA3E4C

ARM_FUNC_START sub_20A3F50
sub_20A3F50:
.incbin "fe11-arm9-base.bin", 0xA3F50, 0xA3FBC - 0xA3F50

ARM_FUNC_START sub_20A3FBC
sub_20A3FBC:
.incbin "fe11-arm9-base.bin", 0xA3FBC, 0xA3FD0 - 0xA3FBC

ARM_FUNC_START sub_20A3FD0
sub_20A3FD0:
.incbin "fe11-arm9-base.bin", 0xA3FD0, 0xA3FE4 - 0xA3FD0

ARM_FUNC_START sub_20A3FE4
sub_20A3FE4:
.incbin "fe11-arm9-base.bin", 0xA3FE4, 0xA40C8 - 0xA3FE4

ARM_FUNC_START sub_20A40C8
sub_20A40C8:
.incbin "fe11-arm9-base.bin", 0xA40C8, 0xA4170 - 0xA40C8

ARM_FUNC_START sub_20A4170
sub_20A4170:
.incbin "fe11-arm9-base.bin", 0xA4170, 0xA4184 - 0xA4170

ARM_FUNC_START sub_20A4184
sub_20A4184:
.incbin "fe11-arm9-base.bin", 0xA4184, 0xA4198 - 0xA4184

ARM_FUNC_START sub_20A4198
sub_20A4198:
.incbin "fe11-arm9-base.bin", 0xA4198, 0xA41A8 - 0xA4198

ARM_FUNC_START sub_20A41A8
sub_20A41A8:
.incbin "fe11-arm9-base.bin", 0xA41A8, 0xA41B8 - 0xA41A8

ARM_FUNC_START sub_20A41B8
sub_20A41B8:
.incbin "fe11-arm9-base.bin", 0xA41B8, 0xA41CC - 0xA41B8

ARM_FUNC_START sub_20A41CC
sub_20A41CC:
.incbin "fe11-arm9-base.bin", 0xA41CC, 0xA41DC - 0xA41CC

ARM_FUNC_START sub_20A41DC
sub_20A41DC:
.incbin "fe11-arm9-base.bin", 0xA41DC, 0xA41EC - 0xA41DC

ARM_FUNC_START sub_20A41EC
sub_20A41EC:
.incbin "fe11-arm9-base.bin", 0xA41EC, 0xA4200 - 0xA41EC

ARM_FUNC_START sub_20A4200
sub_20A4200:
.incbin "fe11-arm9-base.bin", 0xA4200, 0xA4208 - 0xA4200

ARM_FUNC_START sub_20A4208
sub_20A4208:
.incbin "fe11-arm9-base.bin", 0xA4208, 0xA4210 - 0xA4208

ARM_FUNC_START sub_20A4210
sub_20A4210:
.incbin "fe11-arm9-base.bin", 0xA4210, 0xA42F4 - 0xA4210

ARM_FUNC_START sub_20A42F4
sub_20A42F4:
.incbin "fe11-arm9-base.bin", 0xA42F4, 0xA4308 - 0xA42F4

ARM_FUNC_START sub_20A4308
sub_20A4308:
.incbin "fe11-arm9-base.bin", 0xA4308, 0xA4398 - 0xA4308

ARM_FUNC_START sub_20A4398
sub_20A4398:
.incbin "fe11-arm9-base.bin", 0xA4398, 0xA4414 - 0xA4398

ARM_FUNC_START sub_20A4414
sub_20A4414:
.incbin "fe11-arm9-base.bin", 0xA4414, 0xA4430 - 0xA4414

ARM_FUNC_START sub_20A4430
sub_20A4430:
.incbin "fe11-arm9-base.bin", 0xA4430, 0xA44A8 - 0xA4430

ARM_FUNC_START sub_20A44A8
sub_20A44A8:
.incbin "fe11-arm9-base.bin", 0xA44A8, 0xA4520 - 0xA44A8

ARM_FUNC_START sub_20A4520
sub_20A4520:
.incbin "fe11-arm9-base.bin", 0xA4520, 0xA45C0 - 0xA4520

ARM_FUNC_START GetTimer0Control
GetTimer0Control:
.incbin "fe11-arm9-base.bin", 0xA45C0, 0xA45D0 - 0xA45C0

ARM_FUNC_START sub_20A45D0
sub_20A45D0:
.incbin "fe11-arm9-base.bin", 0xA45D0, 0xA465C - 0xA45D0

ARM_FUNC_START sub_20A465C
sub_20A465C:
.incbin "fe11-arm9-base.bin", 0xA465C, 0xA469C - 0xA465C

ARM_FUNC_START sub_20A469C
sub_20A469C:
.incbin "fe11-arm9-base.bin", 0xA469C, 0xA46AC - 0xA469C

ARM_FUNC_START sub_20A46AC
sub_20A46AC:
.incbin "fe11-arm9-base.bin", 0xA46AC, 0xA46BC - 0xA46AC

ARM_FUNC_START sub_20A46BC
sub_20A46BC:
.incbin "fe11-arm9-base.bin", 0xA46BC, 0xA47E8 - 0xA46BC

ARM_FUNC_START sub_20A47E8
sub_20A47E8:
.incbin "fe11-arm9-base.bin", 0xA47E8, 0xA4854 - 0xA47E8

ARM_FUNC_START sub_20A4854
sub_20A4854:
.incbin "fe11-arm9-base.bin", 0xA4854, 0xA48DC - 0xA4854

ARM_FUNC_START sub_20A48DC
sub_20A48DC:
.incbin "fe11-arm9-base.bin", 0xA48DC, 0xA48EC - 0xA48DC

ARM_FUNC_START sub_20A48EC
sub_20A48EC:
.incbin "fe11-arm9-base.bin", 0xA48EC, 0xA49DC - 0xA48EC

ARM_FUNC_START sub_20A49DC
sub_20A49DC:
.incbin "fe11-arm9-base.bin", 0xA49DC, 0xA4A24 - 0xA49DC
