.include "macros.inc"
.section .text

ARM_FUNC_START sub_20A4E90
sub_20A4E90:
.incbin "fe11-arm9-base.bin", 0xA4E90, 0xA4EA0 - 0xA4E90

ARM_FUNC_START sub_20A4EA0
sub_20A4EA0:
.incbin "fe11-arm9-base.bin", 0xA4EA0, 0xA4F20 - 0xA4EA0

ARM_FUNC_START sub_20A4F20
sub_20A4F20:
.incbin "fe11-arm9-base.bin", 0xA4F20, 0xA4F90 - 0xA4F20

ARM_FUNC_START sub_20A4F90
sub_20A4F90:
.incbin "fe11-arm9-base.bin", 0xA4F90, 0xA4FFC - 0xA4F90

ARM_FUNC_START sub_20A4FFC
sub_20A4FFC:
.incbin "fe11-arm9-base.bin", 0xA4FFC, 0xA50C0 - 0xA4FFC

ARM_FUNC_START sub_20A50C0
sub_20A50C0:
.incbin "fe11-arm9-base.bin", 0xA50C0, 0xA5158 - 0xA50C0

ARM_FUNC_START sub_20A5158
sub_20A5158:
.incbin "fe11-arm9-base.bin", 0xA5158, 0xA51C0 - 0xA5158

ARM_FUNC_START sub_20A51C0
sub_20A51C0:
.incbin "fe11-arm9-base.bin", 0xA51C0, 0xA523C - 0xA51C0

ARM_FUNC_START sub_20A523C
sub_20A523C:
.incbin "fe11-arm9-base.bin", 0xA523C, 0xA52C0 - 0xA523C

ARM_FUNC_START sub_20A52C0
sub_20A52C0:
.incbin "fe11-arm9-base.bin", 0xA52C0, 0xA5314 - 0xA52C0

ARM_FUNC_START sub_20A5314
sub_20A5314:
.incbin "fe11-arm9-base.bin", 0xA5314, 0xA54CC - 0xA5314

ARM_FUNC_START sub_20A54CC
sub_20A54CC:
.incbin "fe11-arm9-base.bin", 0xA54CC, 0xA5578 - 0xA54CC

ARM_FUNC_START sub_20A5578
sub_20A5578:
.incbin "fe11-arm9-base.bin", 0xA5578, 0xA5690 - 0xA5578

ARM_FUNC_START sub_20A5690
sub_20A5690:
.incbin "fe11-arm9-base.bin", 0xA5690, 0xA56BC - 0xA5690

ARM_FUNC_START sub_20A56BC
sub_20A56BC:
.incbin "fe11-arm9-base.bin", 0xA56BC, 0xA56D4 - 0xA56BC

ARM_FUNC_START sub_20A56D4
sub_20A56D4:
.incbin "fe11-arm9-base.bin", 0xA56D4, 0xA56F0 - 0xA56D4

ARM_FUNC_START sub_20A56F0
sub_20A56F0:
.incbin "fe11-arm9-base.bin", 0xA56F0, 0xA5704 - 0xA56F0

ARM_FUNC_START sub_20A5704
sub_20A5704:
.incbin "fe11-arm9-base.bin", 0xA5704, 0xA5734 - 0xA5704

ARM_FUNC_START mem_fill
mem_fill:
.incbin "fe11-arm9-base.bin", 0xA5734, 0xA5780 - 0xA5734

ARM_FUNC_START sub_20A5780
sub_20A5780:
.incbin "fe11-arm9-base.bin", 0xA5780, 0xA57B8 - 0xA5780

ARM_FUNC_START sub_20A57B8
sub_20A57B8:
.incbin "fe11-arm9-base.bin", 0xA57B8, 0xA57D4 - 0xA57B8

ARM_FUNC_START sub_20A57D4
sub_20A57D4:
.incbin "fe11-arm9-base.bin", 0xA57D4, 0xA57F8 - 0xA57D4

ARM_FUNC_START sub_20A57F8
sub_20A57F8:
.incbin "fe11-arm9-base.bin", 0xA57F8, 0xA5824 - 0xA57F8

ARM_FUNC_START MI_CpuFill8
MI_CpuFill8:
.incbin "fe11-arm9-base.bin", 0xA5824, 0xA58B8 - 0xA5824

ARM_FUNC_START MI_CpuCopy8
MI_CpuCopy8:
.incbin "fe11-arm9-base.bin", 0xA58B8, 0xA59F8 - 0xA58B8

ARM_FUNC_START sub_20A59F8
sub_20A59F8:
.incbin "fe11-arm9-base.bin", 0xA59F8, 0xA5A00 - 0xA59F8

ARM_FUNC_START sub_20A5A00
sub_20A5A00:
.incbin "fe11-arm9-base.bin", 0xA5A00, 0xA5AE0 - 0xA5A00

ARM_FUNC_START sub_20A5AE0
sub_20A5AE0:
.incbin "fe11-arm9-base.bin", 0xA5AE0, 0xA5C04 - 0xA5AE0

ARM_FUNC_START sub_20A5C04
sub_20A5C04:
.incbin "fe11-arm9-base.bin", 0xA5C04, 0xA5CDC - 0xA5C04

ARM_FUNC_START sub_20A5CDC
sub_20A5CDC:
.incbin "fe11-arm9-base.bin", 0xA5CDC, 0xA5D48 - 0xA5CDC

ARM_FUNC_START sub_20A5D48
sub_20A5D48:
.incbin "fe11-arm9-base.bin", 0xA5D48, 0xA5DB0 - 0xA5D48

ARM_FUNC_START sub_20A5DB0
sub_20A5DB0:
.incbin "fe11-arm9-base.bin", 0xA5DB0, 0xA5E24 - 0xA5DB0

ARM_FUNC_START sub_20A5E24
sub_20A5E24:
.incbin "fe11-arm9-base.bin", 0xA5E24, 0xA5E3C - 0xA5E24

ARM_FUNC_START sub_20A5E3C
sub_20A5E3C:
.incbin "fe11-arm9-base.bin", 0xA5E3C, 0xA5E5C - 0xA5E3C

ARM_FUNC_START sub_20A5E5C
sub_20A5E5C:
.incbin "fe11-arm9-base.bin", 0xA5E5C, 0xA5E84 - 0xA5E5C

ARM_FUNC_START sub_20A5E84
sub_20A5E84:
.incbin "fe11-arm9-base.bin", 0xA5E84, 0xA5EA4 - 0xA5E84

ARM_FUNC_START sub_20A5EA4
sub_20A5EA4:
.incbin "fe11-arm9-base.bin", 0xA5EA4, 0xA5EC4 - 0xA5EA4

ARM_FUNC_START sub_20A5EC4
sub_20A5EC4:
.incbin "fe11-arm9-base.bin", 0xA5EC4, 0xA5EDC - 0xA5EC4

ARM_FUNC_START sub_20A5EDC
sub_20A5EDC:
.incbin "fe11-arm9-base.bin", 0xA5EDC, 0xA5EF4 - 0xA5EDC

ARM_FUNC_START sub_20A5EF4
sub_20A5EF4:
.incbin "fe11-arm9-base.bin", 0xA5EF4, 0xA5F10 - 0xA5EF4

ARM_FUNC_START sub_20A5F10
sub_20A5F10:
.incbin "fe11-arm9-base.bin", 0xA5F10, 0xA5F2C - 0xA5F10

ARM_FUNC_START sub_20A5F2C
sub_20A5F2C:
.incbin "fe11-arm9-base.bin", 0xA5F2C, 0xA5F54 - 0xA5F2C

ARM_FUNC_START sub_20A5F54
sub_20A5F54:
.incbin "fe11-arm9-base.bin", 0xA5F54, 0xA5F7C - 0xA5F54

ARM_FUNC_START sub_20A5F7C
sub_20A5F7C:
.incbin "fe11-arm9-base.bin", 0xA5F7C, 0xA5FE0 - 0xA5F7C

ARM_FUNC_START sub_20A5FE0
sub_20A5FE0:
.incbin "fe11-arm9-base.bin", 0xA5FE0, 0xA6020 - 0xA5FE0

ARM_FUNC_START sub_20A6020
sub_20A6020:
.incbin "fe11-arm9-base.bin", 0xA6020, 0xA6060 - 0xA6020

ARM_FUNC_START sub_20A6060
sub_20A6060:
.incbin "fe11-arm9-base.bin", 0xA6060, 0xA6080 - 0xA6060

ARM_FUNC_START sub_20A6080
sub_20A6080:
.incbin "fe11-arm9-base.bin", 0xA6080, 0xA60A0 - 0xA6080

ARM_FUNC_START sub_20A60A0
sub_20A60A0:
.incbin "fe11-arm9-base.bin", 0xA60A0, 0xA60C8 - 0xA60A0

ARM_FUNC_START sub_20A60C8
sub_20A60C8:
.incbin "fe11-arm9-base.bin", 0xA60C8, 0xA60E8 - 0xA60C8

ARM_FUNC_START sub_20A60E8
sub_20A60E8:
.incbin "fe11-arm9-base.bin", 0xA60E8, 0xA6134 - 0xA60E8

ARM_FUNC_START sub_20A6134
sub_20A6134:
.incbin "fe11-arm9-base.bin", 0xA6134, 0xA6154 - 0xA6134

ARM_FUNC_START sub_20A6154
sub_20A6154:
.incbin "fe11-arm9-base.bin", 0xA6154, 0xA6174 - 0xA6154

ARM_FUNC_START sub_20A6174
sub_20A6174:
.incbin "fe11-arm9-base.bin", 0xA6174, 0xA6194 - 0xA6174

ARM_FUNC_START sub_20A6194
sub_20A6194:
.incbin "fe11-arm9-base.bin", 0xA6194, 0xA61BC - 0xA6194

ARM_FUNC_START sub_20A61BC
sub_20A61BC:
.incbin "fe11-arm9-base.bin", 0xA61BC, 0xA61DC - 0xA61BC

ARM_FUNC_START sub_20A61DC
sub_20A61DC:
.incbin "fe11-arm9-base.bin", 0xA61DC, 0xA61FC - 0xA61DC

ARM_FUNC_START sub_20A61FC
sub_20A61FC:
.incbin "fe11-arm9-base.bin", 0xA61FC, 0xA6224 - 0xA61FC

ARM_FUNC_START sub_20A6224
sub_20A6224:
.incbin "fe11-arm9-base.bin", 0xA6224, 0xA624C - 0xA6224

ARM_FUNC_START sub_20A624C
sub_20A624C:
.incbin "fe11-arm9-base.bin", 0xA624C, 0xA626C - 0xA624C

ARM_FUNC_START sub_20A626C
sub_20A626C:
.incbin "fe11-arm9-base.bin", 0xA626C, 0xA62B0 - 0xA626C

ARM_FUNC_START sub_20A62B0
sub_20A62B0:
.incbin "fe11-arm9-base.bin", 0xA62B0, 0xA62E8 - 0xA62B0

ARM_FUNC_START sub_20A62E8
sub_20A62E8:
.incbin "fe11-arm9-base.bin", 0xA62E8, 0xA62FC - 0xA62E8

ARM_FUNC_START sub_20A62FC
sub_20A62FC:
.incbin "fe11-arm9-base.bin", 0xA62FC, 0xA6310 - 0xA62FC

ARM_FUNC_START sub_20A6310
sub_20A6310:
.incbin "fe11-arm9-base.bin", 0xA6310, 0xA63E4 - 0xA6310

ARM_FUNC_START sub_20A63E4
sub_20A63E4:
.incbin "fe11-arm9-base.bin", 0xA63E4, 0xA64F4 - 0xA63E4

ARM_FUNC_START sub_20A64F4
sub_20A64F4:
.incbin "fe11-arm9-base.bin", 0xA64F4, 0xA657C - 0xA64F4

ARM_FUNC_START sub_20A657C
sub_20A657C:
.incbin "fe11-arm9-base.bin", 0xA657C, 0xA65B4 - 0xA657C

ARM_FUNC_START sub_20A65B4
sub_20A65B4:
.incbin "fe11-arm9-base.bin", 0xA65B4, 0xA6770 - 0xA65B4

ARM_FUNC_START sub_20A6770
sub_20A6770:
.incbin "fe11-arm9-base.bin", 0xA6770, 0xA67DC - 0xA6770

ARM_FUNC_START sub_20A67DC
sub_20A67DC:
.incbin "fe11-arm9-base.bin", 0xA67DC, 0xA6808 - 0xA67DC

ARM_FUNC_START sub_20A6808
sub_20A6808:
.incbin "fe11-arm9-base.bin", 0xA6808, 0xA6858 - 0xA6808

ARM_FUNC_START sub_20A6858
sub_20A6858:
.incbin "fe11-arm9-base.bin", 0xA6858, 0xA6894 - 0xA6858

ARM_FUNC_START sub_20A6894
sub_20A6894:
.incbin "fe11-arm9-base.bin", 0xA6894, 0xA68D0 - 0xA6894

ARM_FUNC_START sub_20A68D0
sub_20A68D0:
.incbin "fe11-arm9-base.bin", 0xA68D0, 0xA68EC - 0xA68D0

ARM_FUNC_START sub_20A68EC
sub_20A68EC:
.incbin "fe11-arm9-base.bin", 0xA68EC, 0xA6910 - 0xA68EC

ARM_FUNC_START sub_20A6910
sub_20A6910:
.incbin "fe11-arm9-base.bin", 0xA6910, 0xA6970 - 0xA6910

ARM_FUNC_START sub_20A6970
sub_20A6970:
.incbin "fe11-arm9-base.bin", 0xA6970, 0xA6998 - 0xA6970

ARM_FUNC_START sub_20A6998
sub_20A6998:
.incbin "fe11-arm9-base.bin", 0xA6998, 0xA69E0 - 0xA6998

ARM_FUNC_START sub_20A69E0
sub_20A69E0:
.incbin "fe11-arm9-base.bin", 0xA69E0, 0xA6A20 - 0xA69E0

ARM_FUNC_START sub_20A6A20
sub_20A6A20:
.incbin "fe11-arm9-base.bin", 0xA6A20, 0xA6A50 - 0xA6A20

ARM_FUNC_START sub_20A6A50
sub_20A6A50:
.incbin "fe11-arm9-base.bin", 0xA6A50, 0xA6A70 - 0xA6A50

ARM_FUNC_START sub_20A6A70
sub_20A6A70:
.incbin "fe11-arm9-base.bin", 0xA6A70, 0xA6AA0 - 0xA6A70

ARM_FUNC_START sub_20A6AA0
sub_20A6AA0:
.incbin "fe11-arm9-base.bin", 0xA6AA0, 0xA6AE4 - 0xA6AA0

ARM_FUNC_START sub_20A6AE4
sub_20A6AE4:
.incbin "fe11-arm9-base.bin", 0xA6AE4, 0xA6B10 - 0xA6AE4

ARM_FUNC_START sub_20A6B10
sub_20A6B10:
.incbin "fe11-arm9-base.bin", 0xA6B10, 0xA6B38 - 0xA6B10

ARM_FUNC_START sub_20A6B38
sub_20A6B38:
.incbin "fe11-arm9-base.bin", 0xA6B38, 0xA6BB4 - 0xA6B38

ARM_FUNC_START sub_20A6BB4
sub_20A6BB4:
.incbin "fe11-arm9-base.bin", 0xA6BB4, 0xA6C24 - 0xA6BB4

ARM_FUNC_START sub_20A6C24
sub_20A6C24:
.incbin "fe11-arm9-base.bin", 0xA6C24, 0xA6CF0 - 0xA6C24

ARM_FUNC_START sub_20A6CF0
sub_20A6CF0:
.incbin "fe11-arm9-base.bin", 0xA6CF0, 0xA6D88 - 0xA6CF0

ARM_FUNC_START sub_20A6D88
sub_20A6D88:
.incbin "fe11-arm9-base.bin", 0xA6D88, 0xA6DD0 - 0xA6D88

ARM_FUNC_START sub_20A6DD0
sub_20A6DD0:
.incbin "fe11-arm9-base.bin", 0xA6DD0, 0xA6DF0 - 0xA6DD0

ARM_FUNC_START sub_20A6DF0
sub_20A6DF0:
.incbin "fe11-arm9-base.bin", 0xA6DF0, 0xA6FA0 - 0xA6DF0

ARM_FUNC_START sub_20A6FA0
sub_20A6FA0:
.incbin "fe11-arm9-base.bin", 0xA6FA0, 0xA6FA8 - 0xA6FA0

ARM_FUNC_START sub_20A6FA8
sub_20A6FA8:
.incbin "fe11-arm9-base.bin", 0xA6FA8, 0xA6FDC - 0xA6FA8

ARM_FUNC_START sub_20A6FDC
sub_20A6FDC:
.incbin "fe11-arm9-base.bin", 0xA6FDC, 0xA7018 - 0xA6FDC

ARM_FUNC_START sub_20A7018
sub_20A7018:
.incbin "fe11-arm9-base.bin", 0xA7018, 0xA7124 - 0xA7018

ARM_FUNC_START sub_20A7124
sub_20A7124:
.incbin "fe11-arm9-base.bin", 0xA7124, 0xA7170 - 0xA7124

ARM_FUNC_START sub_20A7170
sub_20A7170:
.incbin "fe11-arm9-base.bin", 0xA7170, 0xA7194 - 0xA7170

ARM_FUNC_START sub_20A7194
sub_20A7194:
.incbin "fe11-arm9-base.bin", 0xA7194, 0xA721C - 0xA7194

ARM_FUNC_START sub_20A721C
sub_20A721C:
.incbin "fe11-arm9-base.bin", 0xA721C, 0xA7334 - 0xA721C

ARM_FUNC_START FSi_ReleaseCommand
FSi_ReleaseCommand:
.incbin "fe11-arm9-base.bin", 0xA7334, 0xA7390 - 0xA7334

ARM_FUNC_START FSi_TranslateCommand
FSi_TranslateCommand:
.incbin "fe11-arm9-base.bin", 0xA7390, 0xA7520 - 0xA7390

ARM_FUNC_START sub_20A7520
sub_20A7520:
.incbin "fe11-arm9-base.bin", 0xA7520, 0xA7570 - 0xA7520

ARM_FUNC_START sub_20A7570
sub_20A7570:
.incbin "fe11-arm9-base.bin", 0xA7570, 0xA7630 - 0xA7570

ARM_FUNC_START sub_20A7630
sub_20A7630:
.incbin "fe11-arm9-base.bin", 0xA7630, 0xA7664 - 0xA7630

ARM_FUNC_START sub_20A7664
sub_20A7664:
.incbin "fe11-arm9-base.bin", 0xA7664, 0xA7690 - 0xA7664

ARM_FUNC_START sub_20A7690
sub_20A7690:
.incbin "fe11-arm9-base.bin", 0xA7690, 0xA76BC - 0xA7690

ARM_FUNC_START sub_20A76BC
sub_20A76BC:
.incbin "fe11-arm9-base.bin", 0xA76BC, 0xA7754 - 0xA76BC

ARM_FUNC_START sub_20A7754
sub_20A7754:
.incbin "fe11-arm9-base.bin", 0xA7754, 0xA7880 - 0xA7754

ARM_FUNC_START sub_20A7880
sub_20A7880:
.incbin "fe11-arm9-base.bin", 0xA7880, 0xA7A64 - 0xA7880

ARM_FUNC_START sub_20A7A64
sub_20A7A64:
.incbin "fe11-arm9-base.bin", 0xA7A64, 0xA7E10 - 0xA7A64

ARM_FUNC_START sub_20A7E10
sub_20A7E10:
.incbin "fe11-arm9-base.bin", 0xA7E10, 0xA7E90 - 0xA7E10

ARM_FUNC_START sub_20A7E90
sub_20A7E90:
.incbin "fe11-arm9-base.bin", 0xA7E90, 0xA7EB8 - 0xA7E90

ARM_FUNC_START sub_20A7EB8
sub_20A7EB8:
.incbin "fe11-arm9-base.bin", 0xA7EB8, 0xA7EC0 - 0xA7EB8
