.include "macros.inc"
.section .text

ARM_FUNC_START sub_20A4E90
sub_20A4E90:
.incbin "fe11-arm9-base.bin", 0xA4E90, 0xA4EA0 - 0xA4E90

ARM_FUNC_START sub_20A4EA0
sub_20A4EA0:
.incbin "fe11-arm9-base.bin", 0xA4EA0, 0xA4F20 - 0xA4EA0

ARM_FUNC_START sub_20A4F20
sub_20A4F20:
.incbin "fe11-arm9-base.bin", 0xA4F20, 0xA4F90 - 0xA4F20

ARM_FUNC_START sub_20A4F90
sub_20A4F90:
.incbin "fe11-arm9-base.bin", 0xA4F90, 0xA4FFC - 0xA4F90

ARM_FUNC_START sub_20A4FFC
sub_20A4FFC:
.incbin "fe11-arm9-base.bin", 0xA4FFC, 0xA50C0 - 0xA4FFC

ARM_FUNC_START sub_20A50C0
sub_20A50C0:
.incbin "fe11-arm9-base.bin", 0xA50C0, 0xA5158 - 0xA50C0

ARM_FUNC_START sub_20A5158
sub_20A5158:
.incbin "fe11-arm9-base.bin", 0xA5158, 0xA51C0 - 0xA5158

ARM_FUNC_START sub_20A51C0
sub_20A51C0:
.incbin "fe11-arm9-base.bin", 0xA51C0, 0xA523C - 0xA51C0

ARM_FUNC_START sub_20A523C
sub_20A523C:
.incbin "fe11-arm9-base.bin", 0xA523C, 0xA52C0 - 0xA523C

ARM_FUNC_START sub_20A52C0
sub_20A52C0:
.incbin "fe11-arm9-base.bin", 0xA52C0, 0xA5314 - 0xA52C0

ARM_FUNC_START sub_20A5314
sub_20A5314:
.incbin "fe11-arm9-base.bin", 0xA5314, 0xA54CC - 0xA5314

ARM_FUNC_START sub_20A54CC
sub_20A54CC:
.incbin "fe11-arm9-base.bin", 0xA54CC, 0xA5578 - 0xA54CC

ARM_FUNC_START sub_20A5578
sub_20A5578:
.incbin "fe11-arm9-base.bin", 0xA5578, 0xA5690 - 0xA5578

ARM_FUNC_START sub_20A5690
sub_20A5690:
.incbin "fe11-arm9-base.bin", 0xA5690, 0xA56BC - 0xA5690
