.include "macros.inc"
.section .text

ARM_FUNC_START sub_1FF8000
sub_1FF8000:
.incbin "itcm-base.bin", 0x00000, 0x00204 - 0x00000

ARM_FUNC_START sub_1FF8204
sub_1FF8204:
.incbin "itcm-base.bin", 0x00204, 0x00258 - 0x00204

ARM_FUNC_START sub_1FF8258
sub_1FF8258:
.incbin "itcm-base.bin", 0x00258, 0x002B4 - 0x00258

ARM_FUNC_START sub_1FF82B4
sub_1FF82B4:
.incbin "itcm-base.bin", 0x002B4, 0x00580 - 0x002B4

ARM_FUNC_START sub_1FF8580
sub_1FF8580:
.incbin "itcm-base.bin", 0x00580, 0x007A0 - 0x00580

ARM_FUNC_START sub_1FF87A0
sub_1FF87A0:
.incbin "itcm-base.bin", 0x007A0, 0x009C0 - 0x007A0

ARM_FUNC_START sub_1FF89C0
sub_1FF89C0:
.incbin "itcm-base.bin", 0x009C0, 0x00C3C - 0x009C0

ARM_FUNC_START sub_1FF8C3C
sub_1FF8C3C:
.incbin "itcm-base.bin", 0x00C3C, 0x00D88 - 0x00C3C

ARM_FUNC_START sub_1FF8D88
sub_1FF8D88:
.incbin "itcm-base.bin", 0x00D88, 0x00DB8 - 0x00D88

ARM_FUNC_START sub_1FF8DB8
sub_1FF8DB8:
.incbin "itcm-base.bin", 0x00DB8, 0x00E50 - 0x00DB8

ARM_FUNC_START sub_1FF8E50
sub_1FF8E50:
.incbin "itcm-base.bin", 0x00E50, 0x00F24 - 0x00E50

ARM_FUNC_START sub_1FF8F24
sub_1FF8F24:
.incbin "itcm-base.bin", 0x00F24, 0x01000 - 0x00F24

ARM_FUNC_START sub_1FF9000
sub_1FF9000:
.incbin "itcm-base.bin", 0x01000, 0x010D8 - 0x01000

ARM_FUNC_START sub_1FF90D8
sub_1FF90D8:
.incbin "itcm-base.bin", 0x010D8, 0x010F8 - 0x010D8

ARM_FUNC_START sub_1FF90F8
sub_1FF90F8:
.incbin "itcm-base.bin", 0x010F8, 0x011C8 - 0x010F8

ARM_FUNC_START sub_1FF91C8
sub_1FF91C8:
.incbin "itcm-base.bin", 0x011C8, 0x01300 - 0x011C8

ARM_FUNC_START sub_1FF9300
sub_1FF9300:
.incbin "itcm-base.bin", 0x01300, 0x01420 - 0x01300

ARM_FUNC_START sub_1FF9420
sub_1FF9420:
.incbin "itcm-base.bin", 0x01420, 0x015A4 - 0x01420

ARM_FUNC_START sub_1FF95A4
sub_1FF95A4:
.incbin "itcm-base.bin", 0x015A4, 0x01728 - 0x015A4

ARM_FUNC_START sub_1FF9728
sub_1FF9728:
.incbin "itcm-base.bin", 0x01728, 0x01758 - 0x01728

ARM_FUNC_START sub_1FF9758
sub_1FF9758:
.incbin "itcm-base.bin", 0x01758, 0x0176C - 0x01758

ARM_FUNC_START sub_1FF976C
sub_1FF976C:
.incbin "itcm-base.bin", 0x0176C, 0x01780 - 0x0176C

ARM_FUNC_START sub_1FF9780
sub_1FF9780:
.incbin "itcm-base.bin", 0x01780, 0x017A0 - 0x01780

ARM_FUNC_START sub_1FF97A0
sub_1FF97A0:
.incbin "itcm-base.bin", 0x017A0, 0x017F4 - 0x017A0

ARM_FUNC_START sub_1FF97F4
sub_1FF97F4:
.incbin "itcm-base.bin", 0x017F4, 0x01850 - 0x017F4

ARM_FUNC_START sub_1FF9850
sub_1FF9850:
.incbin "itcm-base.bin", 0x01850, 0x01894 - 0x01850

ARM_FUNC_START sub_1FF9894
sub_1FF9894:
.incbin "itcm-base.bin", 0x01894, 0x01948 - 0x01894

ARM_FUNC_START sub_1FF9948
sub_1FF9948:
.incbin "itcm-base.bin", 0x01948, 0x01998 - 0x01948

ARM_FUNC_START sub_1FF9998
sub_1FF9998:
.incbin "itcm-base.bin", 0x01998, 0x019CC - 0x01998

ARM_FUNC_START sub_1FF99CC
sub_1FF99CC:
.incbin "itcm-base.bin", 0x019CC, 0x01A00 - 0x019CC

ARM_FUNC_START sub_1FF9A00
sub_1FF9A00:
.incbin "itcm-base.bin", 0x01A00, 0x01A34 - 0x01A00

ARM_FUNC_START sub_1FF9A34
sub_1FF9A34:
.incbin "itcm-base.bin", 0x01A34, 0x01A68 - 0x01A34

ARM_FUNC_START sub_1FF9A68
sub_1FF9A68:
.incbin "itcm-base.bin", 0x01A68, 0x01A8C - 0x01A68

ARM_FUNC_START sub_1FF9A8C
sub_1FF9A8C:
.incbin "itcm-base.bin", 0x01A8C, 0x01AF8 - 0x01A8C

ARM_FUNC_START sub_1FF9AF8
sub_1FF9AF8:
.incbin "itcm-base.bin", 0x01AF8, 0x01C88 - 0x01AF8

ARM_FUNC_START sub_1FF9C88
sub_1FF9C88:
.incbin "itcm-base.bin", 0x01C88, 0x02218 - 0x01C88

ARM_FUNC_START sub_1FFA218
sub_1FFA218:
.incbin "itcm-base.bin", 0x02218, 0x02690 - 0x02218

ARM_FUNC_START sub_1FFA690
sub_1FFA690:
.incbin "itcm-base.bin", 0x02690, 0x02720 - 0x02690

ARM_FUNC_START sub_1FFA720
sub_1FFA720:
.incbin "itcm-base.bin", 0x02720, 0x02734 - 0x02720

ARM_FUNC_START sub_1FFA734
sub_1FFA734:
.incbin "itcm-base.bin", 0x02734, 0x02748 - 0x02734

ARM_FUNC_START sub_1FFA748
sub_1FFA748:
.incbin "itcm-base.bin", 0x02748, 0x02764 - 0x02748

ARM_FUNC_START sub_1FFA764
sub_1FFA764:
.incbin "itcm-base.bin", 0x02764, 0x02794 - 0x02764

ARM_FUNC_START sub_1FFA794
sub_1FFA794:
.incbin "itcm-base.bin", 0x02794, 0x02828 - 0x02794

ARM_FUNC_START sub_1FFA828
sub_1FFA828:
.incbin "itcm-base.bin", 0x02828, 0x02974 - 0x02828

ARM_FUNC_START sub_1FFA974
sub_1FFA974:
.incbin "itcm-base.bin", 0x02974, 0x02BDC - 0x02974

ARM_FUNC_START sub_1FFABDC
sub_1FFABDC:
.incbin "itcm-base.bin", 0x02BDC, 0x02DC0 - 0x02BDC

ARM_FUNC_START sub_1FFADC0
sub_1FFADC0:
.incbin "itcm-base.bin", 0x02DC0, 0x0308C - 0x02DC0

ARM_FUNC_START sub_1FFB08C
sub_1FFB08C:
.incbin "itcm-base.bin", 0x0308C, 0x03264 - 0x0308C

ARM_FUNC_START sub_1FFB264
sub_1FFB264:
.incbin "itcm-base.bin", 0x03264, 0x03574 - 0x03264

ARM_FUNC_START sub_1FFB574
sub_1FFB574:
.incbin "itcm-base.bin", 0x03574, 0x035DC - 0x03574

ARM_FUNC_START sub_1FFB5DC
sub_1FFB5DC:
.incbin "itcm-base.bin", 0x035DC, 0x03718 - 0x035DC

ARM_FUNC_START sub_1FFB718
sub_1FFB718:
.incbin "itcm-base.bin", 0x03718, 0x0382C - 0x03718

ARM_FUNC_START sub_1FFB82C
sub_1FFB82C:
.incbin "itcm-base.bin", 0x0382C, 0x03934 - 0x0382C

ARM_FUNC_START sub_1FFB934
sub_1FFB934:
.incbin "itcm-base.bin", 0x03934, 0x039BC - 0x03934

ARM_FUNC_START sub_1FFB9BC
sub_1FFB9BC:
.incbin "itcm-base.bin", 0x039BC, 0x03A40 - 0x039BC

ARM_FUNC_START sub_1FFBA40
sub_1FFBA40:
.incbin "itcm-base.bin", 0x03A40, 0x03AEC - 0x03A40

ARM_FUNC_START sub_1FFBAEC
sub_1FFBAEC:
.incbin "itcm-base.bin", 0x03AEC, 0x03B90 - 0x03AEC

ARM_FUNC_START sub_1FFBB90
sub_1FFBB90:
.incbin "itcm-base.bin", 0x03B90, 0x03C90 - 0x03B90

ARM_FUNC_START Root_Proc
Root_Proc:
.incbin "itcm-base.bin", 0x03C90, 0x03CA0 - 0x03C90

ARM_FUNC_START IsRootProcess
IsRootProcess:
.incbin "itcm-base.bin", 0x03CA0, 0x03CB0 - 0x03CA0

ARM_FUNC_START sub_1FFBCB0
sub_1FFBCB0:
.incbin "itcm-base.bin", 0x03CB0, 0x03D3C - 0x03CB0

ARM_FUNC_START AllocateProcess
AllocateProcess:
.incbin "itcm-base.bin", 0x03D3C, 0x03DA4 - 0x03D3C

ARM_FUNC_START sub_1FFBDA4
sub_1FFBDA4:
.incbin "itcm-base.bin", 0x03DA4, 0x03DF4 - 0x03DA4

ARM_FUNC_START sub_1FFBDF4
sub_1FFBDF4:
.incbin "itcm-base.bin", 0x03DF4, 0x03E1C - 0x03DF4

ARM_FUNC_START sub_1FFBE1C
sub_1FFBE1C:
.incbin "itcm-base.bin", 0x03E1C, 0x03E3C - 0x03E1C

ARM_FUNC_START UnlinkProc
UnlinkProc:
.incbin "itcm-base.bin", 0x03E3C, 0x03EB4 - 0x03E3C

ARM_FUNC_START sub_1FFBEB4
sub_1FFBEB4:
.incbin "itcm-base.bin", 0x03EB4, 0x03F78 - 0x03EB4

ARM_FUNC_START Proc_Start
Proc_Start:
.incbin "itcm-base.bin", 0x03F78, 0x03F90 - 0x03F78

ARM_FUNC_START sub_1FFBF90
sub_1FFBF90:
.incbin "itcm-base.bin", 0x03F90, 0x03FD0 - 0x03F90

ARM_FUNC_START sub_1FFBFD0
sub_1FFBFD0:
.incbin "itcm-base.bin", 0x03FD0, 0x03FE0 - 0x03FD0

ARM_FUNC_START sub_1FFBFE0
sub_1FFBFE0:
.incbin "itcm-base.bin", 0x03FE0, 0x04018 - 0x03FE0

ARM_FUNC_START Proc_StartBlocking
Proc_StartBlocking:
.incbin "itcm-base.bin", 0x04018, 0x04030 - 0x04018

ARM_FUNC_START sub_1FFC030
sub_1FFC030:
.incbin "itcm-base.bin", 0x04030, 0x04068 - 0x04030

ARM_FUNC_START sub_1FFC068
sub_1FFC068:
.incbin "itcm-base.bin", 0x04068, 0x040A0 - 0x04068

ARM_FUNC_START sub_1FFC0A0
sub_1FFC0A0:
.incbin "itcm-base.bin", 0x040A0, 0x040E8 - 0x040A0

ARM_FUNC_START sub_1FFC0E8
sub_1FFC0E8:
.incbin "itcm-base.bin", 0x040E8, 0x04174 - 0x040E8

ARM_FUNC_START sub_1FFC174
sub_1FFC174:
.incbin "itcm-base.bin", 0x04174, 0x041E8 - 0x04174

ARM_FUNC_START sub_1FFC1E8
sub_1FFC1E8:
.incbin "itcm-base.bin", 0x041E8, 0x042F4 - 0x041E8

ARM_FUNC_START sub_1FFC2F4
sub_1FFC2F4:
.incbin "itcm-base.bin", 0x042F4, 0x04390 - 0x042F4

ARM_FUNC_START Proc_Run
Proc_Run:
.incbin "itcm-base.bin", 0x04390, 0x043B0 - 0x04390

ARM_FUNC_START sub_1FFC3B0
sub_1FFC3B0:
.incbin "itcm-base.bin", 0x043B0, 0x043F4 - 0x043B0

ARM_FUNC_START sub_1FFC3F4
sub_1FFC3F4:
.incbin "itcm-base.bin", 0x043F4, 0x04404 - 0x043F4

ARM_FUNC_START sub_1FFC404
sub_1FFC404:
.incbin "itcm-base.bin", 0x04404, 0x044E4 - 0x04404

ARM_FUNC_START sub_1FFC4E4
sub_1FFC4E4:
.incbin "itcm-base.bin", 0x044E4, 0x045D4 - 0x044E4

ARM_FUNC_START sub_1FFC5D4
sub_1FFC5D4:
.incbin "itcm-base.bin", 0x045D4, 0x04614 - 0x045D4

ARM_FUNC_START sub_1FFC614
sub_1FFC614:
.incbin "itcm-base.bin", 0x04614, 0x04668 - 0x04614

ARM_FUNC_START sub_1FFC668
sub_1FFC668:
.incbin "itcm-base.bin", 0x04668, 0x046BC - 0x04668

ARM_FUNC_START sub_1FFC6BC
sub_1FFC6BC:
.incbin "itcm-base.bin", 0x046BC, 0x04714 - 0x046BC

ARM_FUNC_START sub_1FFC714
sub_1FFC714:
.incbin "itcm-base.bin", 0x04714, 0x04870 - 0x04714

ARM_FUNC_START sub_1FFC870
sub_1FFC870:
.incbin "itcm-base.bin", 0x04870, 0x048A4 - 0x04870

ARM_FUNC_START sub_1FFC8A4
sub_1FFC8A4:
.incbin "itcm-base.bin", 0x048A4, 0x04970 - 0x048A4

ARM_FUNC_START sub_1FFC970
sub_1FFC970:
.incbin "itcm-base.bin", 0x04970, 0x04984 - 0x04970

ARM_FUNC_START sub_1FFC984
sub_1FFC984:
.incbin "itcm-base.bin", 0x04984, 0x04A2C - 0x04984

ARM_FUNC_START sub_1FFCA2C
sub_1FFCA2C:
.incbin "itcm-base.bin", 0x04A2C, 0x04B04 - 0x04A2C

ARM_FUNC_START sub_1FFCB04
sub_1FFCB04:
.incbin "itcm-base.bin", 0x04B04, 0x04B44 - 0x04B04

ARM_FUNC_START sub_1FFCB44
sub_1FFCB44:
.incbin "itcm-base.bin", 0x04B44, 0x04BB4 - 0x04B44

ARM_FUNC_START sub_1FFCBB4
sub_1FFCBB4:
.incbin "itcm-base.bin", 0x04BB4, 0x04BD8 - 0x04BB4

ARM_FUNC_START sub_1FFCBD8
sub_1FFCBD8:
.incbin "itcm-base.bin", 0x04BD8, 0x04C3C - 0x04BD8

ARM_FUNC_START sub_1FFCC3C
sub_1FFCC3C:
.incbin "itcm-base.bin", 0x04C3C, 0x04CE0 - 0x04C3C
