.include "macros.inc"
.section .text

ARM_FUNC_START func_01FF8000
func_01FF8000:
.incbin "itcm-base.bin", 0x00000, 0x00204 - 0x00000

ARM_FUNC_START func_01FF8204
func_01FF8204:
.incbin "itcm-base.bin", 0x00204, 0x00258 - 0x00204

ARM_FUNC_START func_01FF8258
func_01FF8258:
.incbin "itcm-base.bin", 0x00258, 0x002B4 - 0x00258

ARM_FUNC_START func_01FF82B4
func_01FF82B4:
.incbin "itcm-base.bin", 0x002B4, 0x00580 - 0x002B4

ARM_FUNC_START func_01FF8580
func_01FF8580:
.incbin "itcm-base.bin", 0x00580, 0x007A0 - 0x00580

ARM_FUNC_START func_01FF87A0
func_01FF87A0:
.incbin "itcm-base.bin", 0x007A0, 0x009C0 - 0x007A0

ARM_FUNC_START func_01FF89C0
func_01FF89C0:
.incbin "itcm-base.bin", 0x009C0, 0x00C3C - 0x009C0

ARM_FUNC_START func_01FF8C3C
func_01FF8C3C:
.incbin "itcm-base.bin", 0x00C3C, 0x00D88 - 0x00C3C

ARM_FUNC_START func_01FF8D88
func_01FF8D88:
.incbin "itcm-base.bin", 0x00D88, 0x00DB8 - 0x00D88

ARM_FUNC_START func_01FF8DB8
func_01FF8DB8:
.incbin "itcm-base.bin", 0x00DB8, 0x00E50 - 0x00DB8

ARM_FUNC_START func_01FF8E50
func_01FF8E50:
.incbin "itcm-base.bin", 0x00E50, 0x00F24 - 0x00E50

ARM_FUNC_START func_01FF8F24
func_01FF8F24:
.incbin "itcm-base.bin", 0x00F24, 0x01000 - 0x00F24

ARM_FUNC_START func_01FF9000
func_01FF9000:
.incbin "itcm-base.bin", 0x01000, 0x010D8 - 0x01000

ARM_FUNC_START func_01FF90D8
func_01FF90D8:
.incbin "itcm-base.bin", 0x010D8, 0x010F8 - 0x010D8

ARM_FUNC_START func_01FF90F8
func_01FF90F8:
.incbin "itcm-base.bin", 0x010F8, 0x011C8 - 0x010F8

ARM_FUNC_START func_01FF91C8
func_01FF91C8:
.incbin "itcm-base.bin", 0x011C8, 0x01300 - 0x011C8

ARM_FUNC_START func_01FF9300
func_01FF9300:
.incbin "itcm-base.bin", 0x01300, 0x01420 - 0x01300

ARM_FUNC_START func_01FF9420
func_01FF9420:
.incbin "itcm-base.bin", 0x01420, 0x015A4 - 0x01420

ARM_FUNC_START func_01FF95A4
func_01FF95A4:
.incbin "itcm-base.bin", 0x015A4, 0x01728 - 0x015A4

ARM_FUNC_START func_01FF9728
func_01FF9728:
.incbin "itcm-base.bin", 0x01728, 0x01758 - 0x01728

ARM_FUNC_START func_01FF9758
func_01FF9758:
.incbin "itcm-base.bin", 0x01758, 0x0176C - 0x01758

ARM_FUNC_START func_01FF976C
func_01FF976C:
.incbin "itcm-base.bin", 0x0176C, 0x01780 - 0x0176C

ARM_FUNC_START func_01FF9780
func_01FF9780:
.incbin "itcm-base.bin", 0x01780, 0x017A0 - 0x01780

ARM_FUNC_START func_01FF97A0
func_01FF97A0:
.incbin "itcm-base.bin", 0x017A0, 0x017F4 - 0x017A0

ARM_FUNC_START func_01FF97F4
func_01FF97F4:
.incbin "itcm-base.bin", 0x017F4, 0x01850 - 0x017F4

ARM_FUNC_START func_01FF9850
func_01FF9850:
.incbin "itcm-base.bin", 0x01850, 0x01894 - 0x01850

ARM_FUNC_START func_01FF9894
func_01FF9894:
.incbin "itcm-base.bin", 0x01894, 0x01948 - 0x01894

ARM_FUNC_START func_01FF9948
func_01FF9948:
.incbin "itcm-base.bin", 0x01948, 0x01998 - 0x01948

ARM_FUNC_START func_01FF9998
func_01FF9998:
.incbin "itcm-base.bin", 0x01998, 0x019CC - 0x01998

ARM_FUNC_START func_01FF99CC
func_01FF99CC:
.incbin "itcm-base.bin", 0x019CC, 0x01A00 - 0x019CC

ARM_FUNC_START func_01FF9A00
func_01FF9A00:
.incbin "itcm-base.bin", 0x01A00, 0x01A34 - 0x01A00

ARM_FUNC_START func_01FF9A34
func_01FF9A34:
.incbin "itcm-base.bin", 0x01A34, 0x01A68 - 0x01A34

ARM_FUNC_START func_01FF9A68
func_01FF9A68:
.incbin "itcm-base.bin", 0x01A68, 0x01A8C - 0x01A68

ARM_FUNC_START func_01FF9A8C
func_01FF9A8C:
.incbin "itcm-base.bin", 0x01A8C, 0x01AF8 - 0x01A8C

ARM_FUNC_START func_01FF9AF8
func_01FF9AF8:
.incbin "itcm-base.bin", 0x01AF8, 0x01C88 - 0x01AF8

ARM_FUNC_START func_01FF9C88
func_01FF9C88:
.incbin "itcm-base.bin", 0x01C88, 0x02218 - 0x01C88

ARM_FUNC_START func_01FFA218
func_01FFA218:
.incbin "itcm-base.bin", 0x02218, 0x02690 - 0x02218

ARM_FUNC_START func_01FFA690
func_01FFA690:
.incbin "itcm-base.bin", 0x02690, 0x02720 - 0x02690

ARM_FUNC_START func_01FFA720
func_01FFA720:
.incbin "itcm-base.bin", 0x02720, 0x02734 - 0x02720

ARM_FUNC_START func_01FFA734
func_01FFA734:
.incbin "itcm-base.bin", 0x02734, 0x02748 - 0x02734

ARM_FUNC_START func_01FFA748
func_01FFA748:
.incbin "itcm-base.bin", 0x02748, 0x02764 - 0x02748

ARM_FUNC_START func_01FFA764
func_01FFA764:
.incbin "itcm-base.bin", 0x02764, 0x02794 - 0x02764

ARM_FUNC_START func_01FFA794
func_01FFA794:
.incbin "itcm-base.bin", 0x02794, 0x02828 - 0x02794

ARM_FUNC_START func_01FFA828
func_01FFA828:
.incbin "itcm-base.bin", 0x02828, 0x02974 - 0x02828

ARM_FUNC_START func_01FFA974
func_01FFA974:
.incbin "itcm-base.bin", 0x02974, 0x02BDC - 0x02974

ARM_FUNC_START func_01FFABDC
func_01FFABDC:
.incbin "itcm-base.bin", 0x02BDC, 0x02DC0 - 0x02BDC

ARM_FUNC_START func_01FFADC0
func_01FFADC0:
.incbin "itcm-base.bin", 0x02DC0, 0x0308C - 0x02DC0

ARM_FUNC_START func_01FFB08C
func_01FFB08C:
.incbin "itcm-base.bin", 0x0308C, 0x03264 - 0x0308C

ARM_FUNC_START func_01FFB264
func_01FFB264:
.incbin "itcm-base.bin", 0x03264, 0x03574 - 0x03264

ARM_FUNC_START func_01FFB574
func_01FFB574:
.incbin "itcm-base.bin", 0x03574, 0x035DC - 0x03574

ARM_FUNC_START func_01FFB5DC
func_01FFB5DC:
.incbin "itcm-base.bin", 0x035DC, 0x03718 - 0x035DC

ARM_FUNC_START func_01FFB718
func_01FFB718:
.incbin "itcm-base.bin", 0x03718, 0x0382C - 0x03718

ARM_FUNC_START func_01FFB82C
func_01FFB82C:
.incbin "itcm-base.bin", 0x0382C, 0x03934 - 0x0382C

ARM_FUNC_START Proc_AllocThreadTask
Proc_AllocThreadTask:
.incbin "itcm-base.bin", 0x03934, 0x039BC - 0x03934

ARM_FUNC_START func_01FFB9BC
func_01FFB9BC:
.incbin "itcm-base.bin", 0x039BC, 0x03A40 - 0x039BC

ARM_FUNC_START func_01FFBA40
func_01FFBA40:
.incbin "itcm-base.bin", 0x03A40, 0x03AEC - 0x03A40

ARM_FUNC_START func_01FFBAEC
func_01FFBAEC:
.incbin "itcm-base.bin", 0x03AEC, 0x03B90 - 0x03AEC

ARM_FUNC_START func_01FFBB90
func_01FFBB90:
.incbin "itcm-base.bin", 0x03B90, 0x03C90 - 0x03B90

ARM_FUNC_START Root_Proc
Root_Proc:
.incbin "itcm-base.bin", 0x03C90, 0x03CA0 - 0x03C90

ARM_FUNC_START IsRootProcess
IsRootProcess:
.incbin "itcm-base.bin", 0x03CA0, 0x03CB0 - 0x03CA0

ARM_FUNC_START RunProcessScript
RunProcessScript:
.incbin "itcm-base.bin", 0x03CB0, 0x03D3C - 0x03CB0

ARM_FUNC_START AllocateProcess
AllocateProcess:
.incbin "itcm-base.bin", 0x03D3C, 0x03DA4 - 0x03D3C

ARM_FUNC_START func_01FFBDA4
func_01FFBDA4:
.incbin "itcm-base.bin", 0x03DA4, 0x03DF4 - 0x03DA4

ARM_FUNC_START InsertRootProcess
InsertRootProcess:
.incbin "itcm-base.bin", 0x03DF4, 0x03E1C - 0x03DF4

ARM_FUNC_START InsertChildProcess
InsertChildProcess:
.incbin "itcm-base.bin", 0x03E1C, 0x03E3C - 0x03E1C

ARM_FUNC_START UnlinkProc
UnlinkProc:
.incbin "itcm-base.bin", 0x03E3C, 0x03EB4 - 0x03E3C

ARM_FUNC_START Proc_StartExt
Proc_StartExt:
.incbin "itcm-base.bin", 0x03EB4, 0x03F78 - 0x03EB4

ARM_FUNC_START Proc_Start
Proc_Start:
.incbin "itcm-base.bin", 0x03F78, 0x03F90 - 0x03F78

ARM_FUNC_START func_01FFBF90
func_01FFBF90:
.incbin "itcm-base.bin", 0x03F90, 0x03FD0 - 0x03F90

ARM_FUNC_START func_01FFBFD0
func_01FFBFD0:
.incbin "itcm-base.bin", 0x03FD0, 0x03FE0 - 0x03FD0

ARM_FUNC_START Proc_StartBlockingExt
Proc_StartBlockingExt:
.incbin "itcm-base.bin", 0x03FE0, 0x04018 - 0x03FE0

ARM_FUNC_START Proc_StartBlocking
Proc_StartBlocking:
.incbin "itcm-base.bin", 0x04018, 0x04030 - 0x04018

ARM_FUNC_START func_01FFC030
func_01FFC030:
.incbin "itcm-base.bin", 0x04030, 0x04068 - 0x04030

ARM_FUNC_START func_01FFC068
func_01FFC068:
.incbin "itcm-base.bin", 0x04068, 0x040A0 - 0x04068

ARM_FUNC_START func_01FFC0A0
func_01FFC0A0:
.incbin "itcm-base.bin", 0x040A0, 0x040E8 - 0x040A0

ARM_FUNC_START ClearProc
ClearProc:
.incbin "itcm-base.bin", 0x040E8, 0x04174 - 0x040E8

ARM_FUNC_START Proc_End
Proc_End:
.incbin "itcm-base.bin", 0x04174, 0x041E8 - 0x04174

ARM_FUNC_START RunProcessRecursive
RunProcessRecursive:
.incbin "itcm-base.bin", 0x041E8, 0x042F4 - 0x041E8

ARM_FUNC_START func_01FFC2F4
func_01FFC2F4:
.incbin "itcm-base.bin", 0x042F4, 0x04390 - 0x042F4

ARM_FUNC_START Proc_Run
Proc_Run:
.incbin "itcm-base.bin", 0x04390, 0x043B0 - 0x04390

ARM_FUNC_START Proc_Break
Proc_Break:
.incbin "itcm-base.bin", 0x043B0, 0x043F4 - 0x043B0

ARM_FUNC_START func_01FFC3F4
func_01FFC3F4:
.incbin "itcm-base.bin", 0x043F4, 0x04404 - 0x043F4

ARM_FUNC_START func_01FFC404
func_01FFC404:
.incbin "itcm-base.bin", 0x04404, 0x044E4 - 0x04404

ARM_FUNC_START func_01FFC4E4
func_01FFC4E4:
.incbin "itcm-base.bin", 0x044E4, 0x045D4 - 0x044E4

ARM_FUNC_START func_01FFC5D4
func_01FFC5D4:
.incbin "itcm-base.bin", 0x045D4, 0x04614 - 0x045D4

ARM_FUNC_START func_01FFC614
func_01FFC614:
.incbin "itcm-base.bin", 0x04614, 0x04668 - 0x04614

ARM_FUNC_START func_01FFC668
func_01FFC668:
.incbin "itcm-base.bin", 0x04668, 0x046BC - 0x04668

ARM_FUNC_START OS_IrqHandler
OS_IrqHandler:
.incbin "itcm-base.bin", 0x046BC, 0x04714 - 0x046BC

ARM_FUNC_START OS_IrqHandler_ThreadSwitch
OS_IrqHandler_ThreadSwitch:
.incbin "itcm-base.bin", 0x04714, 0x04870 - 0x04714

ARM_FUNC_START OSi_DoResetSystem
OSi_DoResetSystem:
.incbin "itcm-base.bin", 0x04870, 0x048A4 - 0x04870

ARM_FUNC_START OSi_DoBoot
OSi_DoBoot:
.incbin "itcm-base.bin", 0x048A4, 0x04970 - 0x048A4

ARM_FUNC_START OSi_CpuClear32
OSi_CpuClear32:
.incbin "itcm-base.bin", 0x04970, 0x04984 - 0x04970

ARM_FUNC_START OSi_ReloadRomData
OSi_ReloadRomData:
.incbin "itcm-base.bin", 0x04984, 0x04A2C - 0x04984

ARM_FUNC_START OSi_ReadCardRom32
OSi_ReadCardRom32:
.incbin "itcm-base.bin", 0x04A2C, 0x04B04 - 0x04A2C

ARM_FUNC_START MIi_DmaSetParams
MIi_DmaSetParams:
.incbin "itcm-base.bin", 0x04B04, 0x04B44 - 0x04B04

ARM_FUNC_START MIi_DmaSetParams_wait
MIi_DmaSetParams_wait:
.incbin "itcm-base.bin", 0x04B44, 0x04BB4 - 0x04B44

ARM_FUNC_START MIi_DmaSetParams_noInt
MIi_DmaSetParams_noInt:
.incbin "itcm-base.bin", 0x04BB4, 0x04BD8 - 0x04BB4

ARM_FUNC_START func_01FFCBD8
func_01FFCBD8:
.incbin "itcm-base.bin", 0x04BD8, 0x04C3C - 0x04BD8

ARM_FUNC_START func_01FFCC3C
func_01FFCC3C:
.incbin "itcm-base.bin", 0x04C3C, 0x04CE0 - 0x04C3C
