. = 0x027E0000 - BSS_START; SDK_AUTOLOAD_DTCM_START = .;
. = 0x027E0004 - BSS_START; unk_027E0004 = .;

. = 0x027E0078 - BSS_START; OS_IRQTable = .;
. = 0x027E00E0 - BSS_START; unk_027E00E0 = .;
. = 0x027E1258 - BSS_START; gMainLoopBlocked = .;
. = 0x027E125C - BSS_START; unk_27E125C = .;
. = 0x027E1260 - BSS_START; gClock = .;
. = 0x027E1264 - BSS_START; unk_27E1264 = .;
. = 0x027E1268 - BSS_START; prFreeSpace = .;
. = 0x027E1B9C - BSS_START; AllocListHead = .;
. = 0x027E1BA0 - BSS_START; OSi_IrqThreadQueue = .;
. = 0x027FFC00 - BSS_START; g_nds_bios_ram_h = .;
. = 0x027FFF9C - BSS_START; HW_COMPONENT_PARAM = .;
