.section .rodata

.global __sinit__
__sinit__: @ 0x020C9B10
	.4byte libfunc_unk_20C4CDC
	.4byte libfunc_unk_20C4CFC
	.4byte libfunc_unk_20C4D10
	.4byte libfunc_unk_20C4D28
	.4byte libfunc_unk_20C4D2C
	.4byte libfunc_unk_20C4D58
	.4byte libfunc_unk_20C4FA0
	.4byte libfunc_unk_20C4FCC
	.4byte libfunc_unk_20C5064
	.4byte libfunc_unk_20C5088
	.4byte libfunc_unk_20C50C0
	.4byte libfunc_unk_20C50D8
	.4byte libfunc_unk_20C50F0
	.4byte 0
	.4byte 0
	.4byte 0
	.4byte 0
	.4byte 0
	.4byte 0
	.4byte 0
